"""Calibrate `copula_rho` for the GNN switch predictor's herding copula.

`--raw-stats` measures the raw within-(episode, decision-round, group)
co-switching of the human train split -- the feasibility gate that decides
whether a shared-latent sampler has anything to capture, with no model
marginals involved.

The other modes work on the dumped GNN marginals
(`.../switch_pred_herding_copula/calibration/switch_probs_{train,test}.parquet`)
and estimate the CONDITIONAL latent correlation the sampler will use:

    --mle            binary pairwise-likelihood MLE of the exchangeable
                     Gaussian copula against each row's own predicted
                     p_switch (plan step 5)
    --roundtrip      acceptance gate: recover a known rho from synthetic
                     data generated by the exact model (plan step 6)
    --bootstrap [N]  cluster bootstrap over games for SE / 95% CI, plus the
                     holdout check and the round / cell-size diagnostics
                     (plan step 7)
    --lag1           the same MLE over cross-round pairs of one group's
                     latent, phi_hat = rho_lag1 / rho_hat (plan step 8)
    --preflight      go/no-go: one-step redraws of the human decision cells,
                     independent vs copula at the calibrated rho (plan step 9)
    --write-params   dump rho / phi and their provenance to JSON (step 10)

Method details, conventions, and the estimator history:
notes/autoresearch_log/switch-herding-copula.md (appendix).

Runs locally (pandas/numpy/scipy, no PyG):
    uv run python scripts/baselines/switch_copula_rho.py --raw-stats
    uv run python scripts/baselines/switch_copula_rho.py --mle --roundtrip
"""

import argparse
import os
import sys
import time
from pathlib import Path

os.environ.setdefault("DISABLE_PANDERA_IMPORT_WARNING", "True")
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

TRAIN = ROOT / "experiments/baseline/2group_8agent_50ep_bline_train.csv"
MASK = "switch_valid"
TARGET = "does_switch"
SWITCH_EVERY = 4  # decision cadence -> sets switch_mask / switch_valid
EXPERIMENTS = ("ah_group_switching",)
N_QUAD = 32  # Gauss-Legendre nodes for Phi_2
RHO_MAX = 0.95  # quadrature stays accurate well inside |rho| = 1
P_TINY = 1e-300  # log floor for a cell probability
MIN_PAIRS = 1500  # gate: power
MIN_RHO = 0.10  # gate: signal

# --- the conditional estimator (plan steps 5-10) --------------------------- #
CALIB = ROOT / "artifacts/artificial_humans/switch_pred_herding_copula/calibration"
PROBS = {
    "train": CALIB / "switch_probs_train.parquet",
    "test": CALIB / "switch_probs_test.parquet",
}
BASE_ARTIFACT = ROOT / (
    "artifacts/artificial_humans/switch_pred_opt_50ep_doubled_reanchored"
    "/model/architecture_mlp+rnn+edge__dataset_50ep_doubled.pt"
)
GAME_KEY = ["global_group_id", "episode_id"]  # episode_id alone is NOT unique
CELL_KEY = GAME_KEY + ["round_number", "agent_group"]
P_CLIP = 1e-6  # keeps Phi^-1(1 - p) finite
RHO_GRID = np.arange(0.0, 0.9001, 0.05)  # coarse grid before Brent
RHO_GRID_SIGNED = np.arange(-0.9, 0.9001, 0.05)  # lag-1 boundary diagnostic
N_BOOT = 200  # cluster bootstrap resamples (cost-bounded)
N_ROUNDTRIP = 20  # synthetic replicates per rho_true
RHO_TRUES = (0.05, 0.1, 0.2, 0.3, 0.4, 0.5)
SEED = 42
NLL0_TOL = 1e-10  # step-6 gate: pair_nll(0) vs the closed form
BIAS_TOL = 0.03  # step-6 gate: max |bias| of the round-trip

# planner's read-only feasibility numbers (note 5), printed for eyeball check
EXPECTED = dict(
    eligible=1515,
    rate=0.29372937,
    per_round={3: 0.4290, 7: 0.3026, 11: 0.2601, 15: 0.2292, 19: 0.2434},
    cells=374,
    cells_ge2=330,
    hist={1: 44, 2: 46, 3: 51, 4: 95, 5: 47, 6: 41, 7: 35, 8: 15},
    pairs=3009,
    n11=341,
    n11_exp=215.6,
    odds_ratio=2.748,
    phi=0.2125,
    rho=0.3554,
)

from scipy.special import ndtr, ndtri  # noqa: E402

GL_X, GL_W = np.polynomial.legendre.leggauss(N_QUAD)


def f(x):
    """Unrounded float for the log."""
    return repr(float(x))


def line(label, value, expected=None, note=""):
    """One aligned `label  value  EXPECTED e` row."""
    exp = "" if expected is None else f"EXPECTED {expected}"
    print(f"{label:<30} {str(value):<23} {exp}{note}".rstrip())


# --------------------------------------------------------------------------- #
# data: the repo's own parsing, keeping the (episode, round, group) index
# --------------------------------------------------------------------------- #
def load_rows(path=TRAIN, switch_every=SWITCH_EVERY):
    """Every `switch_valid` decision row of `path`, with its cell index.

    Parsed by `parse_agent_rounds` -- the same labelling the switch models
    train on. The cell is (episode, decision round, PRE-switch group), which
    is the simulation's `state["agent_group"]` at that round (log note D7).
    """
    from aimanager.generic.data import parse_agent_rounds

    df = pd.read_csv(path)
    df = df[df["experiment_name"].isin(EXPERIMENTS)]
    df = df[~df["global_group_id"].str.contains("(flipped)", regex=False)]
    n_games = df["global_group_id"].nunique()
    parsed = parse_agent_rounds(df.copy(), switch_every=switch_every)
    rows = parsed[parsed[MASK]].copy()
    keys = ["group_idx", "round_number", "agent_group"]
    cell = rows.groupby(keys, sort=True).ngroup().to_numpy()
    return dict(
        y=rows[TARGET].to_numpy().astype(np.int64),
        cell=cell.astype(np.int64),
        episode=rows["group_idx"].to_numpy().astype(np.int64),
        round=rows["round_number"].to_numpy().astype(np.int64),
        group=rows["agent_group"].to_numpy().astype(np.int64),
        player=rows["player_idx"].to_numpy().astype(np.int64),
        n_games=int(n_games),
    )


# --------------------------------------------------------------------------- #
# cells and within-cell pairs
# --------------------------------------------------------------------------- #
def blocks(cell):
    """Sort rows by cell; return (order, starts, sizes) with each cell a
    contiguous block (what np.add.reduceat needs)."""
    order = np.argsort(cell, kind="stable")
    k = cell[order]
    starts = np.flatnonzero(np.r_[True, k[1:] != k[:-1]])
    sizes = np.diff(np.r_[starts, len(k)])
    return order, starts, sizes


def pair_index(cell):
    """Row indices (i, j), i < j, of every within-cell pair."""
    order, starts, sizes = blocks(cell)
    ii, jj = [], []
    for s, n in zip(starts, sizes):
        if n < 2:
            continue
        idx = order[s : s + n]
        a, b = np.triu_indices(n, k=1)
        ii.append(idx[a])
        jj.append(idx[b])
    if not ii:
        return np.array([], np.int64), np.array([], np.int64)
    return np.concatenate(ii), np.concatenate(jj)


# --------------------------------------------------------------------------- #
# bivariate normal CDF (Drezner-Wesolowsky, Gauss-Legendre, vectorised) --
# shared with the pairwise MLE of plan step 5
# --------------------------------------------------------------------------- #
def bvn_cdf(h, k, rho):
    """Phi_2(h, k; rho) elementwise over the arrays h, k for a scalar rho."""
    base = ndtr(h) * ndtr(k)
    if rho == 0.0:
        return base
    r = 0.5 * rho * (GL_X + 1.0)  # [Q] nodes on (0, rho)
    om = 1.0 - r**2
    hh, kk = h[:, None], k[:, None]
    dens = np.exp(-(hh**2 - 2.0 * r * hh * kk + kk**2) / (2.0 * om)) / np.sqrt(om)
    return base + (0.5 * rho / (2.0 * np.pi)) * (dens @ GL_W)


def check_bvn(n=400, seed=42):
    """Max abs deviation of bvn_cdf from scipy's mvn CDF on random points."""
    try:
        from scipy.stats import multivariate_normal as mvn
    except ImportError:  # pragma: no cover
        return None
    rng = np.random.default_rng(seed)
    h = rng.uniform(-4.0, 4.0, n)
    k = rng.uniform(-4.0, 4.0, n)
    worst = 0.0
    for rho in (0.05, 0.2, 0.5, 0.8, 0.9):
        mine = bvn_cdf(h, k, rho)
        cov = [[1.0, rho], [rho, 1.0]]
        ref = np.array(
            [mvn.cdf([hi, ki], mean=[0.0, 0.0], cov=cov) for hi, ki in zip(h, k)]
        )
        worst = max(worst, float(np.abs(mine - ref).max()))
    return worst


# --------------------------------------------------------------------------- #
# the pooled 2x2 pair table and its unconditional tetrachoric rho
# --------------------------------------------------------------------------- #
def pair_table(y, ii, jj):
    """Symmetrised 2x2 co-switching table over the within-cell pairs.

    A within-cell pair is unordered, so each pair enters the table in both
    orderings and the table is halved: n10 = n01 = (n10_raw + n01_raw) / 2.
    That is what makes the margins exchangeable -- the convention the
    reference numbers in note 5 use, and the one the exchangeable copula
    assumes. Counts sum to len(ii).
    """
    a = y[ii].astype(bool)
    b = y[jj].astype(bool)
    n11 = float((a & b).sum())
    n00 = float((~a & ~b).sum())
    off = float((a & ~b).sum() + (~a & b).sum()) / 2.0
    return n11, off, off, n00


def table_stats(n11, n10, n01, n00):
    """(pair-slot switch rate, expected n11 under independence, OR, phi)."""
    n = n11 + n10 + n01 + n00
    p_bar = (n11 + n10) / n  # both margins, symmetrised
    exp11 = n * p_bar**2
    odds = (n11 * n00) / (n10 * n01)
    phi = (n11 * n00 - n10 * n01) / np.sqrt(
        (n11 + n10) * (n01 + n00) * (n11 + n01) * (n10 + n00)
    )
    return float(p_bar), float(exp11), float(odds), float(phi)


def tetrachoric_rho(n11, n10, n01, n00):
    """Latent correlation of a 2x2 table by bivariate-normal MLE.

    Thresholds are the marginal MLEs, h = Phi^-1(1 - p_bar) on both axes;
    rho then maximises the multinomial log-likelihood of the four cells.
    Returns (rho_hat, nll(rho_hat), nll(0)).
    """
    from scipy.optimize import minimize_scalar

    n = n11 + n10 + n01 + n00
    h = np.array([ndtri(1.0 - (n11 + n10) / n)])
    k = np.array([ndtri(1.0 - (n11 + n01) / n)])

    def nll(rho):
        p00 = bvn_cdf(h, k, float(np.clip(rho, -RHO_MAX, RHO_MAX)))[0]
        p10 = ndtr(k)[0] - p00  # X > h, Y <= k
        p01 = ndtr(h)[0] - p00
        p11 = 1.0 - ndtr(h)[0] - ndtr(k)[0] + p00
        cells = np.array([p11, p10, p01, p00])
        counts = np.array([n11, n10, n01, n00])
        return -float((counts * np.log(np.maximum(cells, P_TINY))).sum())

    res = minimize_scalar(
        nll, bounds=(-RHO_MAX, RHO_MAX), method="bounded", options=dict(xatol=1e-9)
    )
    return float(res.x), float(res.fun), nll(0.0)


# --------------------------------------------------------------------------- #
# --raw-stats
# --------------------------------------------------------------------------- #
def raw_stats(rows):
    """Print the feasibility numbers and return the gate verdict string."""
    y, cell = rows["y"], rows["cell"]
    order, starts, sizes = blocks(cell)
    ii, jj = pair_index(cell)
    n_pairs = len(ii)

    print("\n=== eligible switch decisions ===")
    line(f"n eligible ({MASK})", len(y), EXPECTED["eligible"])
    line("overall switch rate", f(y.mean()), EXPECTED["rate"])
    line("per decision round", "rate", note="EXPECTED  n eligible")
    for r in np.unique(rows["round"]):
        m = rows["round"] == r
        line(
            f"  round {r}",
            f(y[m].mean()),
            f"{EXPECTED['per_round'][int(r)]:<8}",
            f"  {int(m.sum())}",
        )

    print("\n=== (episode, decision round, group) cells ===")
    line("n cells", len(sizes), EXPECTED["cells"])
    line("n cells with >= 2 eligible", int((sizes >= 2).sum()), EXPECTED["cells_ge2"])
    hist = np.bincount(sizes)
    line("cell size histogram", "count", note="EXPECTED")
    for s in range(1, len(hist)):
        if hist[s]:
            line(f"  size {s}", int(hist[s]), EXPECTED["hist"].get(s, "-"))
    line("n within-cell pairs", n_pairs, EXPECTED["pairs"])

    n11, n10, n01, n00 = pair_table(y, ii, jj)
    p_bar, exp11, odds, phi = table_stats(n11, n10, n01, n00)
    print("\n=== co-switching over within-cell pairs (symmetrised 2x2) ===")
    line("n11 (both switch)", int(n11), EXPECTED["n11"])
    line("n10 = n01 (one switches)", f(n10))
    line("n00 (neither switches)", int(n00))
    line(
        "pair-slot switch rate",
        f(p_bar),
        note=f"(row rate {f(y.mean())}; big cells switch less)",
    )
    line("expected n11 (independence)", f(exp11), EXPECTED["n11_exp"])
    line("odds ratio", f(odds), EXPECTED["odds_ratio"])
    line("phi coefficient", f(phi), EXPECTED["phi"])

    rho, nll_hat, nll0 = tetrachoric_rho(n11, n10, n01, n00)
    err = check_bvn()
    print("\n=== unconditional tetrachoric (latent-scale) rho ===")
    line("rho (2x2 bivar-normal MLE)", f(rho), EXPECTED["rho"])
    line("  nll(rho_hat)", f(nll_hat))
    line("  nll(0)", f(nll0))
    line("  2*(nll(0) - nll(rho_hat))", f(2.0 * (nll0 - nll_hat)))
    print(
        f"  Phi_2 nodes={N_QUAD}, max abs err vs scipy mvn="
        f"{'unchecked' if err is None else f(err)}"
    )
    print(
        "  UNCONDITIONAL: shared observable features are still in here. The "
        "conditional\n  rho against the GNN marginals (plan step 5) will be "
        "smaller; this is the ceiling."
    )

    ok = n_pairs >= MIN_PAIRS and rho > MIN_RHO
    if ok:
        return f"PASS (pairs {n_pairs} >= {MIN_PAIRS}, rho {f(rho)} > {MIN_RHO})"
    why = []
    if n_pairs < MIN_PAIRS:
        why.append(f"within-cell pairs {n_pairs} < {MIN_PAIRS}")
    if rho <= MIN_RHO:
        why.append(f"tetrachoric rho {f(rho)} <= {MIN_RHO}")
    return "ESCALATE: " + "; ".join(why)


# --------------------------------------------------------------------------- #
# the dumped GNN marginals: one row per (game, round, player)
# --------------------------------------------------------------------------- #
def load_probs(path):
    """`switch_valid` rows of a probability dump, with cell and game index.

    The game key is BOTH (global_group_id, episode_id) -- episode_id alone
    repeats across sessions (log note 9). A cell is (game, round_number,
    agent_group): the pre-switch membership the simulation conditions on
    (ruling D7). p is clipped off 0/1 so Phi^-1 stays finite; with the
    dumped range (0.0298, 0.9491) the clip never binds here.
    """
    df = pd.read_parquet(path)
    df = df[df[MASK]].copy()
    df = df.sort_values(CELL_KEY + ["player_idx"], kind="stable")
    return dict(
        p=np.clip(df["p_switch"].to_numpy(np.float64), P_CLIP, 1.0 - P_CLIP),
        y=df[TARGET].to_numpy().astype(np.int64),
        cell=df.groupby(CELL_KEY, sort=False).ngroup().to_numpy().astype(np.int64),
        game=df.groupby(GAME_KEY, sort=False).ngroup().to_numpy().astype(np.int64),
        round=df["round_number"].to_numpy().astype(np.int64),
        group=df["agent_group"].to_numpy().astype(np.int64),
        player=df["player_idx"].to_numpy().astype(np.int64),
        n_games=int(df.groupby(GAME_KEY, sort=False).ngroups),
        path=path,
    )


# --------------------------------------------------------------------------- #
# the conditional estimator: binary pairwise-likelihood MLE (plan step 5)
# --------------------------------------------------------------------------- #
def thresholds(p):
    """t = Phi^-1(1 - p), so P(z > t) = p = P(switch).

    Switching is the UPPER tail of the latent everywhere in this file --
    estimator, generator and (later) sampler share the orientation, so the
    round-trip of step 6 tests exactly the model that is fitted.
    """
    return ndtri(1.0 - p)


def pair_terms(p, y, ii, jj):
    """Rectangle constants of every pair: P(y_i, y_j | rho) = c + s * P11.

    P11 = P(z_i > t_i, z_j > t_j) = Phi_2(-t_i, -t_j; rho), hence
    (1,1): 0 + P11,  (1,0): p_i - P11,  (0,1): p_j - P11,
    (0,0): 1 - p_i - p_j + P11.
    Returns (H, K, c, s) with H = -t_i, K = -t_j. Only c and s depend on the
    outcomes, so a bootstrap resample or a synthetic outcome vector reuses
    the same corner points.
    """
    pi, pj = p[ii], p[jj]
    a, b = y[ii].astype(bool), y[jj].astype(bool)
    c = np.where(a & b, 0.0, np.where(a, pi, np.where(b, pj, 1.0 - pi - pj)))
    s = np.where(a == b, 1.0, -1.0)
    t = thresholds(p)
    return -t[ii], -t[jj], c, s


def pair_nll(H, K, c, s, rho):
    """Negative summed pairwise log-likelihood at `rho` (floored before log)."""
    prob = c + s * bvn_cdf(H, K, rho)
    return -float(np.log(np.maximum(prob, P_TINY)).sum())


def independence_nll(p, y, ii, jj):
    """Closed-form pairwise nll under independence -- what pair_nll(0) must
    reproduce: the sum of the two Bernoulli log-likelihoods of each pair."""
    q = np.where(y.astype(bool), p, 1.0 - p)
    return -float((np.log(q[ii]) + np.log(q[jj])).sum())


def rho_mle(H, K, c, s, grid=RHO_GRID):
    """Maximise the pairwise log-likelihood: coarse grid, then bounded Brent.
    Returns (rho_hat, nll(rho_hat), nll(0), n_evals)."""
    from scipy.optimize import minimize_scalar

    lo_b, hi_b = float(grid[0]), float(grid[-1])
    evals = [0]

    def nll(rho):
        evals[0] += 1
        return pair_nll(H, K, c, s, float(np.clip(rho, lo_b, hi_b)))

    vals = [nll(r) for r in grid]
    b = int(np.argmin(vals))
    lo = float(grid[max(b - 1, 0)])
    hi = float(grid[min(b + 1, len(grid) - 1)])
    res = minimize_scalar(
        nll, bounds=(lo, hi), method="bounded", options=dict(xatol=1e-6)
    )
    zero = np.flatnonzero(np.isclose(grid, 0.0))
    nll0 = vals[int(zero[0])] if len(zero) else nll(0.0)
    return float(res.x), float(res.fun), float(nll0), evals[0]


def mle_on_rows(rows, sel=None, grid=RHO_GRID):
    """(rho, n_pairs, n_rows, n_cells>=2) over a row subset's within-cell
    pairs -- pairs are rebuilt inside the subset, never inherited."""
    y = rows["y"]
    sel = np.ones(len(y), bool) if sel is None else sel
    p_s, y_s, cell_s = rows["p"][sel], y[sel], rows["cell"][sel]
    ii, jj = pair_index(cell_s)
    H, K, c, s = pair_terms(p_s, y_s, ii, jj)
    rho = rho_mle(H, K, c, s, grid=grid)[0]
    _, _, sizes = blocks(cell_s)
    return rho, len(ii), int(sel.sum()), int((sizes >= 2).sum())


# --------------------------------------------------------------------------- #
# cross-round pairs of one group's latent (plan step 8)
# --------------------------------------------------------------------------- #
def cross_pairs(rows, step=SWITCH_EVERY):
    """Row indices (i at decision round r, j at round r + step) belonging to
    the same (game, group) -- the lag-1 pairs whose model correlation is
    rho * phi.

    The block key is the GROUP's latent, so each row joins the block of the
    group it belonged to AT ITS OWN ROUND: a player who switched at r sits
    in the other group's block at r + step. Every i x j combination of the
    two blocks enters once, INCLUDING the same player at both rounds -- the
    per-agent noise is redrawn each round, so the implied correlation is
    rho * phi for every cross-round pair, same player or not. Only rounds
    exactly one decision epoch apart are paired.
    """
    idx = {}
    for pos, key in enumerate(
        zip(rows["game"].tolist(), rows["round"].tolist(), rows["group"].tolist())
    ):
        idx.setdefault(key, []).append(pos)
    ii, jj = [], []
    for (g, r, grp), a in sorted(idx.items()):
        b = idx.get((g, r + step, grp))
        if b is None:
            continue
        a_arr, b_arr = np.array(a, np.int64), np.array(b, np.int64)
        ii.append(np.repeat(a_arr, len(b_arr)))
        jj.append(np.tile(b_arr, len(a_arr)))
    if not ii:
        return np.array([], np.int64), np.array([], np.int64)
    return np.concatenate(ii), np.concatenate(jj)


def phi_verdict(phi_hat, ci):
    """The plan's drop rule for arm B: (kept?, reason)."""
    if not np.isfinite(phi_hat) or phi_hat <= 0.0:
        return False, f"phi_hat {f(phi_hat)} <= 0"
    if ci[0] <= 0.0 <= ci[1]:
        return False, f"95% CI [{f(ci[0])}, {f(ci[1])}] includes 0"
    return True, ""


# --------------------------------------------------------------------------- #
# cluster bootstrap over games
# --------------------------------------------------------------------------- #
def per_game_pairs(game, ii, jj):
    """{game: pair positions}; every pair sits inside a single game, so
    resampling games resamples whole pair blocks. Games contributing no
    pair map to an empty array."""
    g = game[ii]
    assert np.array_equal(g, game[jj]), "pair crosses games"
    return {int(k): np.flatnonzero(g == k) for k in np.unique(game)}


def bootstrap_games(pairsets, game_ids, n_boot, seed):
    """Cluster bootstrap over games. `pairsets` is a list of
    (H, K, c, s, per_game); all sets see the SAME game resample, so the
    returned rho arrays are paired and their ratio is a valid phi draw.

    Every resample is refit on the full RHO_GRID -- the precedent narrows
    the bracket around the full-sample estimate for cost, but 3009 pairs
    are cheap enough here and a narrowed bracket censored the upper tail.
    """
    rng = np.random.default_rng(seed)
    out = [np.empty(n_boot) for _ in pairsets]
    for b in range(n_boot):
        draw = rng.choice(game_ids, size=len(game_ids), replace=True)
        for o, (H, K, c, s, per_game) in zip(out, pairsets):
            pos = np.concatenate([per_game[int(g)] for g in draw])
            o[b] = rho_mle(H[pos], K[pos], c[pos], s[pos])[0]
    return out


# --------------------------------------------------------------------------- #
# round-trip acceptance gate (plan step 6)
# --------------------------------------------------------------------------- #
def sample_copula_binary(t, inv, n_cells, rho, rng):
    """Outcomes from exactly the model being estimated: one shared latent per
    cell at weight sqrt(rho), fresh per-agent noise, switch = upper tail.

    w = sqrt(rho) z_cell + sqrt(1 - rho) eps ~ N(0, 1) and y = 1[w > t] is
    the z-side form of `u = ndtr(w) > 1 - p` -- identical, minus one
    ndtr/Phi^-1 round-trip.
    """
    z = rng.standard_normal(n_cells)
    eps = rng.standard_normal(len(t))
    w = np.sqrt(rho) * z[inv] + np.sqrt(1.0 - rho) * eps
    return (w > t).astype(np.int64)


def roundtrip(rows, rho_trues=RHO_TRUES, n_rep=N_ROUNDTRIP, seed=SEED):
    """(rho_true, mean rho_hat, bias, sd) per rho_true, on the REAL dumped
    marginals and the REAL cell structure."""
    p, cell = rows["p"], rows["cell"]
    t = thresholds(p)
    _, inv = np.unique(cell, return_inverse=True)
    n_cells = int(inv.max()) + 1
    ii, jj = pair_index(cell)
    rng = np.random.default_rng(seed)
    out = []
    for rho_true in rho_trues:
        hats = np.empty(n_rep)
        for k in range(n_rep):
            y = sample_copula_binary(t, inv, n_cells, rho_true, rng)
            H, K, c, s = pair_terms(p, y, ii, jj)
            hats[k] = rho_mle(H, K, c, s)[0]
        out.append(
            (
                float(rho_true),
                float(hats.mean()),
                float(hats.mean() - rho_true),
                float(hats.std(ddof=1)),
            )
        )
    return out


# --------------------------------------------------------------------------- #
# pre-flight go/no-go (plan step 9)
# --------------------------------------------------------------------------- #
N_PREFLIGHT = 500  # redraw repeats
DECISION_ROUNDS = (3, 7, 11, 15, 19)
PARAMS_JSON = CALIB / "copula_params.json"
# PR #140 reference numbers (full simulations, all rounds -- levels differ
# from this one-step-ahead check; the within-setting comparison is the point)
PR140 = dict(mean=(6.09, 5.28, 5.46), p8=(0.144, 0.018, 0.030))


def load_preflight(path):
    """Decision-round rows of a dump, UNFILTERED: ineligible players count
    toward group sizes but are never redrawn (they cannot switch)."""
    df = pd.read_parquet(path)
    df = df[df["round_number"].isin(DECISION_ROUNDS)].copy()
    df = df.sort_values(CELL_KEY + ["player_idx"], kind="stable")
    elig = df[MASK].to_numpy().astype(bool)
    sub = df[df[MASK]]
    return dict(
        p=np.clip(df["p_switch"].to_numpy(np.float64)[elig], P_CLIP, 1.0 - P_CLIP),
        y=df[TARGET].to_numpy().astype(np.int64)[elig],
        cell=sub.groupby(CELL_KEY, sort=False).ngroup().to_numpy(np.int64),
        gr_all=df.groupby(GAME_KEY + ["round_number"], sort=False)
        .ngroup()
        .to_numpy(np.int64),
        group_all=df["agent_group"].to_numpy(np.int64),
        round_all=df["round_number"].to_numpy(np.int64),
        elig=elig,
        path=path,
    )


def preflight_stats(pf, Y):
    """One-step post-switch group stats for outcome draws `Y` (n_elig, R).

    Post sizes at s+1 apply the drawn switches to the actual pre-switch
    memberships; ineligible players stay. Returns (mean larger-group size,
    P(larger == 8), sd of per-cell switch count, round-3 mean |size diff|,
    round-3 sd |size diff|), averaged over the R draws where applicable.
    """
    if Y.ndim == 1:
        Y = Y[:, None]
    n_r = Y.shape[1]
    gr_e = pf["gr_all"][pf["elig"]]
    group_e = pf["group_all"][pf["elig"]]
    n_gr = int(pf["gr_all"].max()) + 1
    # pre-switch sizes of group 0 per (game, round); total is always 8
    n0 = np.bincount(pf["gr_all"], weights=(pf["group_all"] == 0), minlength=n_gr)
    out0 = np.zeros((n_gr, n_r))
    out1 = np.zeros((n_gr, n_r))
    np.add.at(out0, gr_e[group_e == 0], Y[group_e == 0])
    np.add.at(out1, gr_e[group_e == 1], Y[group_e == 1])
    post0 = n0[:, None] - out0 + out1
    larger = np.maximum(post0, 8.0 - post0)
    # per-cell switch counts (a cell = one group's eligible members)
    n_cells = int(pf["cell"].max()) + 1
    counts = np.zeros((n_cells, n_r))
    np.add.at(counts, pf["cell"], Y)
    sd_out = counts.std(axis=0, ddof=1).mean()
    # the founding exodus: segregation created at the first decision
    is_r3 = (
        np.bincount(pf["gr_all"], weights=(pf["round_all"] == 3), minlength=n_gr) > 0
    )
    absdiff = np.abs(2.0 * post0[is_r3] - 8.0)
    return (
        float(larger.mean()),
        float((larger == 8.0).mean()),
        float(sd_out),
        float(absdiff.mean()),
        float(absdiff.std(ddof=1)),
    )


def run_preflight(n_rep=N_PREFLIGHT, seed=SEED):
    """Go/no-go: does the copula move the one-step group aggregates from the
    independence floor toward the human realizations? rho is READ from the
    params JSON -- never a tunable input of this check."""
    import json

    params = json.loads(PARAMS_JSON.read_text())
    rho = float(params["rho"])
    pf = load_preflight(PROBS["train"])
    t = thresholds(pf["p"])
    n_cells = int(pf["cell"].max()) + 1
    print(f"\n=== pre-flight (plan step 9): one-step redraws, R={n_rep} ===")
    print(f"data      {Path(pf['path']).relative_to(ROOT)}")
    print(f"rho       {f(rho)}  (from {PARAMS_JSON.relative_to(ROOT)})")
    rng = np.random.default_rng(seed)
    y_ind = np.empty((len(t), n_rep), dtype=np.int64)
    y_cop = np.empty((len(t), n_rep), dtype=np.int64)
    for k in range(n_rep):
        y_ind[:, k] = sample_copula_binary(t, pf["cell"], n_cells, 0.0, rng)
        y_cop[:, k] = sample_copula_binary(t, pf["cell"], n_cells, rho, rng)
    hum = preflight_stats(pf, pf["y"])
    ind = preflight_stats(pf, y_ind)
    cop = preflight_stats(pf, y_cop)
    names = (
        "larger-group mean (s+1)",
        "P(larger group = 8)",
        "sd per-cell switch count",
        "round-3 mean |size diff|",
        "round-3 sd |size diff|",
    )
    print(f"{'':<28}{'human':>12}{'independent':>14}{'copula':>12}")
    for i, name in enumerate(names):
        print(f"{name:<28}{hum[i]:>12.4f}{ind[i]:>14.4f}{cop[i]:>12.4f}")
    print(
        "PR #140 reference (full sims, all rounds; levels not comparable "
        "to one-step):"
    )
    print(
        f"{'  mean / P(=8)':<28}"
        f"{PR140['mean'][0]:>7.2f}/{PR140['p8'][0]:.3f}"
        f"{PR140['mean'][1]:>9.2f}/{PR140['p8'][1]:.3f}"
        f"{PR140['mean'][2]:>7.2f}/{PR140['p8'][2]:.3f}"
    )
    print(
        "\nCAVEAT: arm B's AR(1) persistence (phi = "
        f"{f(params.get('phi'))}) cannot appear in a ONE-STEP check; this "
        "pre-flight bounds ARM A only. The cumulative multi-round effect "
        "is what Stage 1 measures."
    )
    closed = []
    for i in (0, 2):
        gap_h = hum[i] - ind[i]
        share = (cop[i] - ind[i]) / gap_h if gap_h != 0 else float("nan")
        closed.append(share)
        print(f"copula closes {100 * share:.1f}% of the {names[i]} gap")
    if closed[1] < 0.10:
        print(
            "ESCALATE-CANDIDATE: copula closes <10% of the switch-count-sd "
            "gap (orchestrator rules; see the caveat above)"
        )
    return hum, ind, cop, closed


# --------------------------------------------------------------------------- #
# params JSON (plan step 10)
# --------------------------------------------------------------------------- #
def write_params(path, info):
    """Dump the estimates plus full provenance (data, base artifact, HEAD)."""
    import hashlib
    import json
    import subprocess

    out = dict(info)
    out["base_artifact"] = str(BASE_ARTIFACT.relative_to(ROOT))
    out["base_artifact_sha256"] = hashlib.sha256(BASE_ARTIFACT.read_bytes()).hexdigest()
    out["git_head"] = subprocess.check_output(
        ["git", "-C", str(ROOT), "rev-parse", "HEAD"], text=True
    ).strip()
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(out, indent=2, sort_keys=True) + "\n")
    print(f"\nwrote {path}")
    for k in sorted(out):
        print(f"  {k}: {out[k]}")


# --------------------------------------------------------------------------- #
# modes
# --------------------------------------------------------------------------- #
def run_raw_stats():
    rows = load_rows()
    print(f"data      {TRAIN.relative_to(ROOT)}")
    print(
        f"  games={rows['n_games']} experiments={list(EXPERIMENTS)} "
        f"switch_every={SWITCH_EVERY} mask={MASK} target={TARGET}"
    )
    print("  cell key = (episode, decision round, pre-switch agent_group)")
    print(f"\nGATE: {raw_stats(rows)}")


def describe(rows):
    """Header for a probability dump; returns its within-cell pairs."""
    _, _, sizes = blocks(rows["cell"])
    ii, jj = pair_index(rows["cell"])
    print(f"data      {Path(rows['path']).relative_to(ROOT)}")
    print(
        f"  games={rows['n_games']} rows={len(rows['y'])} "
        f"switch rate={f(rows['y'].mean())} mean p={f(rows['p'].mean())} "
        f"p range=[{f(rows['p'].min())}, {f(rows['p'].max())}]"
    )
    print(
        f"  cells={len(sizes)} cells>=2={int((sizes >= 2).sum())} "
        f"within-cell pairs={len(ii)}"
    )
    print(f"  cell key = ({', '.join(CELL_KEY)})")
    return ii, jj


def section_mle(rows, ii, jj):
    """Plan step 5 + half of the step-6 gate. Returns (rho_hat, ok)."""
    p, y = rows["p"], rows["y"]
    H, K, c, s = pair_terms(p, y, ii, jj)
    t0 = time.time()
    rho_hat, nll_hat, nll0, n_ev = rho_mle(H, K, c, s)
    dt = time.time() - t0
    ind = independence_nll(p, y, ii, jj)
    gap = abs(nll0 - ind)
    ok = gap <= NLL0_TOL
    print("\n=== rho: binary pairwise-likelihood MLE (train split) ===")
    print(f"rho_hat                      {f(rho_hat)}")
    print(f"  pairwise nll(rho_hat)      {f(nll_hat)}")
    print(f"  pairwise nll(0)            {f(nll0)}")
    print(
        f"  2*(nll(0) - nll(rho_hat))  {f(2.0 * (nll0 - nll_hat))}  "
        f"(pairwise LR, not chi2-calibrated)"
    )
    print(f"  n_pairs={len(ii)}  nll evals={n_ev}  fit {dt:.2f}s")
    print("\n=== GATE 1/2: pair_nll(0) vs the closed-form independence nll ===")
    print(f"  closed-form independence   {f(ind)}")
    print(f"  |difference|               {f(gap)}")
    print(f"  -> {'PASS' if ok else 'FAIL'} (tolerance {NLL0_TOL})")
    return rho_hat, ok


def section_roundtrip(rows):
    """Plan step 6: recovery of a known rho. Returns (rows, ok)."""
    t0 = time.time()
    table = roundtrip(rows)
    bias = max(abs(b) for _, _, b, _ in table)
    ok = bias <= BIAS_TOL
    print(
        f"\n=== GATE 2/2: round-trip recovery ({N_ROUNDTRIP} replicates per "
        f"rho, seed {SEED}) ==="
    )
    print("rho_true   mean rho_hat           bias                   sd")
    for rho_true, mean, b, sd in table:
        print(f"{rho_true:<10.2f} {f(mean):<22} {f(b):<22} {f(sd)}")
    print(
        f"max |bias| = {f(bias)}  -> {'PASS' if ok else 'FAIL'} "
        f"(tolerance {BIAS_TOL})   [{time.time() - t0:.1f}s]"
    )
    return table, ok


def section_bootstrap(rows, ii, jj, rho_hat, n_boot):
    """Plan step 7: SE / CI, the holdout check, and the diagnostic splits."""
    p, y = rows["p"], rows["y"]
    H, K, c, s = pair_terms(p, y, ii, jj)
    per_game = per_game_pairs(rows["game"], ii, jj)
    game_ids = np.array(sorted(per_game))
    t0 = time.time()
    (boot,) = bootstrap_games([(H, K, c, s, per_game)], game_ids, n_boot, SEED)
    se = float(boot.std(ddof=1))
    ci = (float(np.percentile(boot, 2.5)), float(np.percentile(boot, 97.5)))
    print(
        f"\n=== cluster bootstrap ({n_boot} resamples over {len(game_ids)} games) ==="
    )
    print(f"rho_hat                      {f(rho_hat)}")
    print(f"  SE                         {f(se)}")
    print(f"  95% percentile CI          [{f(ci[0])}, {f(ci[1])}]")
    print(
        f"  bootstrap min/max          {f(boot.min())} / {f(boot.max())}"
        f"   [{time.time() - t0:.1f}s]"
    )

    te = load_probs(PROBS["test"])
    rho_te, pr_te, rows_te, cells_te = mle_on_rows(te)
    print(
        f"\nOUT-OF-SAMPLE CHECK ONLY ({Path(te['path']).name}, games={te['n_games']})"
    )
    print(
        f"  rho={f(rho_te)}  rows={rows_te} cells>=2={cells_te} pairs={pr_te}"
        f"  (the marginal model saw all 50 games -- ruling D1)"
    )

    print("\n=== DIAGNOSTIC splits (never a selection criterion) ===")
    print("split                        rho                     n")

    def split(label, sel):
        rho, n_pr, n_rows, n_cells = mle_on_rows(rows, sel)
        print(
            f"{label:<28} {f(rho):<23} rows={n_rows} cells>=2={n_cells} "
            f"pairs={n_pr}"
        )

    for r in np.unique(rows["round"]):
        split(f"decision round {r}", rows["round"] == r)
    order, starts, sizes = blocks(rows["cell"])
    size_of_cell = dict(zip(rows["cell"][order][starts], sizes))
    row_size = np.array([size_of_cell[k] for k in rows["cell"]])
    split("cell size 2-3", np.isin(row_size, (2, 3)))
    split("cell size 4+", row_size >= 4)
    return se, ci


def section_lag1(rows, ii, jj, rho_hat, n_boot):
    """Plan step 8: rho_lag1, phi_hat, and the drop verdict."""
    p, y = rows["p"], rows["y"]
    ic, jc = cross_pairs(rows)
    same = int((rows["player"][ic] == rows["player"][jc]).sum())
    Hc, Kc, cc, sc = pair_terms(p, y, ic, jc)
    rho_lag1, nll_hat, nll0, _ = rho_mle(Hc, Kc, cc, sc)
    rho_signed = rho_mle(Hc, Kc, cc, sc, grid=RHO_GRID_SIGNED)[0]
    phi_hat = rho_lag1 / rho_hat if rho_hat > 0 else float("nan")
    print("\n=== arm B: lag-1 persistence of the group latent ===")
    print(
        f"cross-round pairs            {len(ic)}  "
        f"(same player at both rounds: {same})"
    )
    print(f"rho_lag1                     {f(rho_lag1)}")
    print(f"  pairwise nll(rho_lag1)     {f(nll_hat)}")
    print(f"  2*(nll(0) - nll(rho_lag1)) {f(2.0 * (nll0 - nll_hat))}")
    print(
        f"  signed-grid refit          {f(rho_signed)}  DIAGNOSTIC: "
        f"the estimate when rho < 0 is allowed (boundary check)"
    )
    print(f"phi_hat = rho_lag1 / rho_hat {f(phi_hat)}")

    H, K, c, s = pair_terms(p, y, ii, jj)
    pg_w = per_game_pairs(rows["game"], ii, jj)
    pg_c = per_game_pairs(rows["game"], ic, jc)
    game_ids = np.array(sorted(pg_w))
    t0 = time.time()
    bw, bc = bootstrap_games(
        [(H, K, c, s, pg_w), (Hc, Kc, cc, sc, pg_c)], game_ids, n_boot, SEED
    )
    phi_b = np.where(bw > 0, bc / np.where(bw > 0, bw, 1.0), np.nan)
    finite = phi_b[np.isfinite(phi_b)]
    ci = (float(np.percentile(finite, 2.5)), float(np.percentile(finite, 97.5)))
    keep, why = phi_verdict(phi_hat, ci)
    print(f"cluster bootstrap ({n_boot} resamples, rho and rho_lag1 refit per draw)")
    print(f"  phi 95% percentile CI      [{f(ci[0])}, {f(ci[1])}]  <- the drop rule")
    print(f"  phi bootstrap median       {f(np.median(finite))}")
    print(
        f"  phi SE                     {f(finite.std(ddof=1))}  "
        f"(a RATIO: heavy-tailed as the denominator approaches 0, no finite "
        f"moments -- read the percentile CI, not this)"
    )
    print(f"  degenerate draws (rho=0)   {int(len(phi_b) - len(finite))}")
    print(f"  draws with rho < 0.01      {int((bw < 0.01).sum())}")
    print(f"  rho bootstrap min/max      {f(bw.min())} / {f(bw.max())}")
    print(
        f"  rho_lag1 min/mean/max      {f(bc.min())} / {f(bc.mean())} / "
        f"{f(bc.max())}   [{time.time() - t0:.1f}s]"
    )
    print(f"VERDICT: {'ARM B KEPT' if keep else 'ARM B DROPPED -- ' + why}")
    return rho_lag1, phi_hat, ci, keep, why, len(ic)


# --------------------------------------------------------------------------- #
def main():
    t0 = time.time()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--raw-stats",
        action="store_true",
        help="feasibility gate: raw within-cell co-switching of the human "
        "train split, no model marginals involved",
    )
    ap.add_argument(
        "--mle",
        action="store_true",
        help="plan step 5: binary pairwise-likelihood MLE of rho against "
        "the dumped GNN marginals, plus the pair_nll(0) gate",
    )
    ap.add_argument(
        "--roundtrip",
        action="store_true",
        help="plan step 6: recover a known rho from synthetic copula data",
    )
    ap.add_argument(
        "--bootstrap",
        type=int,
        nargs="?",
        const=N_BOOT,
        default=None,
        metavar="N",
        help=f"plan step 7: cluster bootstrap over games (default {N_BOOT}), "
        f"holdout check and diagnostic splits",
    )
    ap.add_argument(
        "--lag1",
        action="store_true",
        help="plan step 8: rho_lag1 over cross-round pairs, phi_hat and the "
        "arm-B drop verdict",
    )
    ap.add_argument(
        "--preflight",
        action="store_true",
        help="plan step 9: one-step redraws of the human decision cells, "
        "independent vs copula at the rho of the params JSON",
    )
    ap.add_argument(
        "--write-params",
        metavar="PATH",
        default=None,
        help="plan step 10: write the params JSON (implies --mle, "
        "--bootstrap and --lag1)",
    )
    args = ap.parse_args()

    if args.write_params:
        args.mle = True
        args.lag1 = True
        if args.bootstrap is None:
            args.bootstrap = N_BOOT
    conditional = bool(args.mle or args.roundtrip or args.bootstrap or args.lag1)
    if not (args.raw_stats or conditional or args.preflight):
        ap.error(
            "nothing to do: pass --raw-stats, --mle, --roundtrip, "
            "--bootstrap [N], --lag1, --preflight or --write-params PATH"
        )

    if args.raw_stats:
        run_raw_stats()

    if args.preflight:
        run_preflight()

    if conditional:
        rows = load_probs(PROBS["train"])
        ii, jj = describe(rows)
        err = check_bvn()
        print(
            f"  Phi_2 nodes={N_QUAD}, max abs err vs scipy mvn="
            f"{'unchecked' if err is None else f(err)}"
        )
        rho_hat, gate1 = section_mle(rows, ii, jj)
        gate2 = None
        if args.roundtrip:
            _, gate2 = section_roundtrip(rows)
            print(
                f"\nACCEPTANCE (plan step 6): "
                f"{'PASS' if gate1 and gate2 else 'FAIL'}"
            )
        se = ci = None
        if args.bootstrap:
            se, ci = section_bootstrap(rows, ii, jj, rho_hat, args.bootstrap)
        lag = None
        if args.lag1:
            lag = section_lag1(rows, ii, jj, rho_hat, args.bootstrap or N_BOOT)
        if args.write_params:
            rho_lag1, phi_hat, phi_ci, keep, why, n_cross = lag
            _, _, sizes = blocks(rows["cell"])
            write_params(
                args.write_params,
                dict(
                    rho=rho_hat,
                    rho_se=se,
                    rho_ci=list(ci),
                    rho_lag1=rho_lag1,
                    phi=phi_hat if keep else None,
                    phi_ci=list(phi_ci),
                    phi_drop_reason=None if keep else why,
                    estimator="pairwise_mle",
                    cell_key="_".join(CELL_KEY),
                    n_pairs=len(ii),
                    n_cross_pairs=n_cross,
                    n_cells=int(len(sizes)),
                    n_cells_ge2=int((sizes >= 2).sum()),
                    n_rows=int(len(rows["y"])),
                    n_games=rows["n_games"],
                    n_bootstrap=args.bootstrap,
                    seed=SEED,
                    data_file=str(PROBS["train"].relative_to(ROOT)),
                    data_file_holdout=str(PROBS["test"].relative_to(ROOT)),
                ),
            )

    print(f"total runtime {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()
