"""Emit the six RL-manager training configs of the two-worlds comparison.

The claim the experiment makes is that the two arms differ in nothing but
which artificial humans they are trained against, so the configs are generated
from one template rather than written by hand: the only per-arm input is
ARMS[arm], the only per-run input is the seed.

    python scripts/rl_two_worlds/make_configs.py [--pilot]

`--pilot` additionally writes the short arm-NEW run used to price the design.
"""

import argparse
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT_DIR = os.path.join(ROOT, "configs/training/rl_manager")

SEEDS = (42, 43, 44)

# Shared in both arms: the validity model is plumbing, not a slot.
VALID_MODEL = "artifacts/artificial_humans/raven_script_22/model/rnn_False__dataset_full.pt"  # noqa: E501

# Arm OLD's switch slot is an open design decision, not a free choice, so both
# candidates are named here rather than one being quietly picked. `03_2g8a_sum`
# names `switch_pred_opt_50ep`, which was trained under the pre-#123 anchoring
# while `environment.step()` now runs the re-anchored convention -- feeding it
# round s-1 values where it expects round s. That lag would sit in arm OLD and
# not in arm NEW, so any difference between the arms would be partly the
# convention rather than the clones. The alternative keeps the same switch
# trunk at the earliest artifact that is anchoring-correct.
OLD_SWITCH_FAITHFUL = (
    "artifacts/artificial_humans/switch_pred_opt_50ep/"
    "model/architecture_mlp+rnn+edge__dataset_50ep__epochs_375.pt"
)
OLD_SWITCH_REANCHORED = (
    "artifacts/artificial_humans/switch_pred_opt_50ep_doubled_reanchored/"
    "model/architecture_mlp+rnn+edge__dataset_50ep_doubled.pt"
)

# The four artificial-human slots. Everything else in the template is shared.
ARMS = {
    # The 2g8a stack 03_2g8a_sum.yml was written against. Its contribution
    # checkpoint (epochs_1000) and its autoregressive punisher were both
    # deleted from main; see the log file for where each was recovered.
    "old": {
        "label": "the 2022 stack 03_2g8a_sum.yml names",
        "artificial_humans": (
            "artifacts/artificial_humans/group_switching_contribution_50ep/"
            "model/architecture_node+edge+rnn__dataset_50ep__epochs_1000.pt"
        ),
        "switch_model": OLD_SWITCH_FAITHFUL,
        "opponent_manager": (
            "artifacts/artificial_humans/punishment_autoregressive_50ep/"
            "model/architecture_node+edge+autoregressive__dataset_50ep"
            "__epochs_7500.pt"
        ),
    },
    # The current frontier: the contribution trunk with the per-group virtual
    # node, the direct stimulus skip and the stamped herding copula; the
    # joint-exodus switch model; the multinomial punisher with the ceiling
    # indicator and its severity copula, conditioned on round t's
    # contribution. Paths taken from the sim configs on the base branch.
    "new": {
        "label": "the current frontier stack",
        "artificial_humans": (
            "artifacts/artificial_humans/"
            "group_switching_contribution_50ep_vnode_stimulus_skip_herding_copula/"
            "model/architecture_node+edge+rnn__dataset_50ep__epochs_575.pt"
        ),
        "switch_model": (
            "artifacts/artificial_humans/switch_joint_exodus/"
            "model/architecture_mlp+rnn+edge__dataset_50ep_doubled.pt"
        ),
        "opponent_manager": (
            "artifacts/baselines/punishment_multinomial_ceiling_severity_copula"
            ".joblib"
        ),
    },
}

BLOCKED_BANNER = """\
# !! NOT YET RUN -- BLOCKED. Do not submit this config.
# The pre-run code review (notes/reviews/rl-manager-review.md, on branch
# review/rl-manager) names defects that would invalidate a training run:
#   D1  a punishment aimed at a timed-out player costs the manager nothing,
#       yet every artificial human is still shown it -- a free lever the
#       learner can identify from `contribution_valid`, which sits in its own
#       x_encoding. Both arms.
#   D2  the reward discards a timed-out player's payoff, which the real game
#       paid: an unlearnable shock worth ~31% of the reward on the group-rounds
#       that contain a timeout. Both arms.
#   D4  arm OLD only -- see OLD_SWITCH_FAITHFUL above.
# D1/D2 are being fixed elsewhere; the arm-OLD switch slot is a maintainer
# decision. See notes/autoresearch_log/rl-manager-two-worlds.md."""

TEMPLATE = """\
# AUTOGENERATED by scripts/rl_two_worlds/make_configs.py -- do not hand-edit.
#
{blocked}
#
# Two-worlds RL manager comparison ({job_id}).
# Arm {arm_upper}: {label}.
# Every key below except the four artifact paths and `seed` is byte-identical
# across all six runs of the experiment, and identical to the hyperparameters
# of configs/training/rl_manager/03_2g8a_sum.yml -- nothing is tuned.
# See notes/autoresearch_log/rl-manager-two-worlds.md.

artificial_humans: {artificial_humans}
artificial_humans_valid: {valid_model}
switch_model: {switch_model}
opponent_manager: {opponent_manager}
artificial_humans_model: "graph"
job_id: {job_id}
seed: {seed}

manager_args:
  opt_args:
      lr: 2.e-4
  gamma: 0.98
  eps: 0.1
  target_update_freq: 1000
  model_args:
      hidden_size: 100
      add_rnn: true
      add_edge_model: true
      add_global_model: False
      x_encoding:
        - name: contribution
          n_levels: 21
          encoding: numeric
        - name: prev_punishment
          n_levels: 31
          encoding: numeric
        - etype: bool
          name: contribution_valid
        - etype: bool
          name: in_group
      b_encoding:
        - name: round_number
          n_levels: 32
          encoding: onehot

replay_memory_args:
  n_episodes: 100

n_update_steps: {n_update_steps}
eval_period: {eval_period}
training_batch_size: 1

env_args:
  n_groups: 2
  n_agents: 8
  agent_groups: [0, 0, 0, 0, 1, 1, 1, 1]
  rl_group_id: 0
  switch_every: 4
  n_contributions: 21
  n_punishments: 31
  n_rounds: 24
  batch_size: 1000
  reward_mode: sum

device: "cuda"
output_dir: "artifacts/manager/{job_id}"
basedir: "."
"""


def write(job_id, arm, seed, n_update_steps, eval_period):
    spec = ARMS[arm]
    text = TEMPLATE.format(
        blocked=BLOCKED_BANNER,
        job_id=job_id,
        arm_upper=arm.upper(),
        label=spec["label"],
        artificial_humans=spec["artificial_humans"],
        switch_model=spec["switch_model"],
        opponent_manager=spec["opponent_manager"],
        valid_model=VALID_MODEL,
        seed=seed,
        n_update_steps=n_update_steps,
        eval_period=eval_period,
    )
    path = os.path.join(OUT_DIR, f"{job_id}.yml")
    with open(path, "w") as f:
        f.write(text)
    print(path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pilot", action="store_true")
    args = ap.parse_args()

    for arm in ARMS:
        for seed in SEEDS:
            write(f"two_worlds_{arm}_s{seed}", arm, seed, 4000, 20)
    if args.pilot:
        write("two_worlds_pilot_new", "new", 42, 40, 10)
        write("two_worlds_pilot_old", "old", 42, 40, 10)


if __name__ == "__main__":
    main()
