"""Emit the RL-manager training configs for the new-clones experiment.

Originally a two-arm comparison; arm OLD was dropped by the maintainer as too
hard to replicate faithfully (its switch artifact carries the pre-#123
anchoring, see notes/autoresearch_log/rl-manager-two-worlds.md note 7). What
remains is one world -- the current corrected clones -- and one question: does
a manager trained against them punish at all, what does its policy look like,
and does it beat the artificial punisher.

The three runs differ only in `seed`, so the configs are generated rather than
hand-written and that claim is mechanical.

    python scripts/rl_two_worlds/make_configs.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT_DIR = os.path.join(ROOT, "configs/training/rl_manager")

SEEDS = (42, 43, 44)

# The current frontier stack: the contribution trunk with the per-group virtual
# node, the direct stimulus skip and the stamped herding copula; the
# joint-exodus switch model; the multinomial punisher with the ceiling
# indicator and its severity copula, conditioned on round t's contribution.
# Paths read off the sim configs, not guessed.
CONTRIBUTION_MODEL = (
    "artifacts/artificial_humans/"
    "group_switching_contribution_50ep_vnode_stimulus_skip_herding_copula/"
    "model/architecture_node+edge+rnn__dataset_50ep__epochs_575.pt"
)
SWITCH_MODEL = (
    "artifacts/artificial_humans/switch_joint_exodus/"
    "model/architecture_mlp+rnn+edge__dataset_50ep_doubled.pt"
)
# Also the baseline the learned policies are scored against, not only the
# opponent: it is this project's clone of a human manager.
OPPONENT_PUNISHER = (
    "artifacts/baselines/punishment_multinomial_ceiling_severity_copula.joblib"
)
# Plumbing, not a slot.
VALID_MODEL = "artifacts/artificial_humans/raven_script_22/model/rnn_False__dataset_full.pt"  # noqa: E501

# The real runs must train on the common pool -- what a real manager was
# actually paid -- rather than on `sum` (the sum of contributor payoffs, which
# prices punishment ~5x too high and is ~63% headcount by variance; review
# S1). The mode is being added on auto/manager-common-pool-reward and is not on
# this branch yet, so `sum` stands here only so the cost pilot can run: wall
# clock does not depend on the reward. Flip this one constant when that branch
# lands, and regenerate.
REWARD_MODE = "common_pool"

BLOCKED_BANNER = """\
# !! NOT YET RUN -- BLOCKED on the free-punishment defect (review D1): a
# punishment aimed at a timed-out player costs the manager nothing, yet every
# artificial human is still shown it. Under this config's common-pool reward
# punishment is costly everywhere EXCEPT on those cells, so a free lever
# strictly dominates a paid one and a learner has every reason to find it.
# Clear it with auto/free-punishment-fix and re-run
# scripts/rl_two_worlds/launch_guards.py before submitting.
# See notes/autoresearch_log/rl-manager-two-worlds.md."""

PILOT_BANNER = """\
# COST PILOT -- a wall-clock measurement, not a result. 40 update steps, run
# only to price a full 4000-step run before committing three A100-days. Its
# reward mode and the unfixed free-punishment defect do not affect timing, and
# nothing it produces is science. Do not read its policy."""

TEMPLATE = """\
# AUTOGENERATED by scripts/rl_two_worlds/make_configs.py -- do not hand-edit.
#
{banner}
#
# RL manager vs the current corrected clones ({job_id}).
# Every key below except `seed`, `job_id` and `output_dir` is byte-identical
# across the three runs, and the hyperparameters are those of
# configs/training/rl_manager/03_2g8a_sum.yml -- nothing is tuned.

artificial_humans: {contribution_model}
artificial_humans_valid: {valid_model}
switch_model: {switch_model}
opponent_manager: {opponent_punisher}
artificial_humans_model: "graph"
job_id: {job_id}
seed: {seed}

manager_args:
  opt_args:
      lr: 2.e-4
  gamma: 0.98
  eps: 0.1
  target_update_freq: 1000
  model_args:
      hidden_size: 100
      add_rnn: true
      add_edge_model: true
      add_global_model: False
      x_encoding:
        - name: contribution
          n_levels: 21
          encoding: numeric
        - name: prev_punishment
          n_levels: 31
          encoding: numeric
        - etype: bool
          name: contribution_valid
        - etype: bool
          name: in_group
      b_encoding:
        - name: round_number
          n_levels: 32
          encoding: onehot

replay_memory_args:
  n_episodes: 100

n_update_steps: {n_update_steps}
eval_period: {eval_period}
training_batch_size: 1

env_args:
  n_groups: 2
  n_agents: 8
  agent_groups: [0, 0, 0, 0, 1, 1, 1, 1]
  rl_group_id: 0
  switch_every: 4
  n_contributions: 21
  n_punishments: 31
  n_rounds: 24
  batch_size: 1000
  reward_mode: {reward_mode}

device: "cuda"
output_dir: "artifacts/manager/{job_id}"
basedir: "."
"""


def write(job_id, seed, n_update_steps, eval_period, banner):
    text = TEMPLATE.format(
        banner=banner,
        job_id=job_id,
        contribution_model=CONTRIBUTION_MODEL,
        switch_model=SWITCH_MODEL,
        opponent_punisher=OPPONENT_PUNISHER,
        valid_model=VALID_MODEL,
        seed=seed,
        n_update_steps=n_update_steps,
        eval_period=eval_period,
        reward_mode=REWARD_MODE,
    )
    path = os.path.join(OUT_DIR, f"{job_id}.yml")
    with open(path, "w") as f:
        f.write(text)
    print(path)


def main():
    for seed in SEEDS:
        write(f"rl_new_clones_s{seed}", seed, 4000, 20, BLOCKED_BANNER)
    write("rl_new_clones_pilot", 42, 40, 10, PILOT_BANNER)


if __name__ == "__main__":
    main()
