artificial_humans:
  group_switching:
    contribution_model: artifacts/artificial_humans/group_switching_contribution_35ep/model/architecture_node+edge+rnn__dataset_35ep.pt
    valid_model: artifacts/artificial_humans/raven_script_22/model/rnn_False__dataset_full.pt
    switch_model: artifacts/artificial_humans/switch_pred_opt/model/architecture_mlp+rnn+edge__dataset_35ep.pt
managers:
  punishment_human_manager:
    type: human
    path: artifacts/artificial_humans/punishment_autoregressive/model/architecture_node+edge+autoregressive__dataset_35ep.pt

switch_every: 4
n_episode_steps: 24
n_episodes: 50
n_groups: 2
n_agents: 8
n_contributions: 21
n_punishments: 31
n_rounds: 24

basedir: .
pilot_data_file: experiments/2group_8agent_35ep.csv
pilot_experiment_name_map:
  ah_group_switching: pilot human manager
