artificial_humans:
  pseudo_group:
    contribution_model: artifacts/artificial_humans/combined_old_new/model/architecture_node+edge+rnn__dataset_full.pt
    valid_model: artifacts/artificial_humans/raven_script_22/model/rnn_False__dataset_full.pt
  combined_pseudo_group:
    contribution_model: artifacts/artificial_humans/combined_old_new_group_switching/model/architecture_node+edge+rnn__dataset_full.pt
    valid_model: artifacts/artificial_humans/raven_script_22/model/rnn_False__dataset_full.pt
  pre_group:
    contribution_model: artifacts/artificial_humans/raven_script_test/model/architecture_node+edge+rnn__dataset_full.pt
    valid_model: artifacts/artificial_humans/raven_script_22/model/rnn_False__dataset_full.pt
managers:
  latest_manager:
    type: rl
    path: artifacts/manager/pr7/model/raven_per_group_manager.pt

n_episode_steps: 24
n_episodes: 100
n_groups: 2
n_agents: 8
n_contributions: 21
n_punishments: 31
n_rounds: 24

output_dir: plots/simulation/ah_group_testing_8_combined
figure_name: combined_pseudo_group_vs_pre_group
base_dir: .
