artificial_humans:
  group_switching:
    contribution_model: artifacts/artificial_humans/group_switching_contribution_50ep/model/architecture_node+edge+rnn__dataset_50ep__epochs_575.pt
    valid_model: artifacts/artificial_humans/raven_script_22/model/rnn_False__dataset_full.pt
    switch_model: artifacts/artificial_humans/switch_pred_opt_50ep_doubled/model/architecture_mlp+rnn+edge__dataset_50ep_doubled.pt
managers:
  punishment_human_manager:
    type: human
    path: artifacts/artificial_humans/punishment_rnn_edge_50ep_doubled/model/architecture_node+edge+rnn__dataset_50ep_doubled.pt

switch_every: 4
n_episode_steps: 24
n_episodes: 100
n_groups: 2
n_agents: 8
agent_groups: [0, 0, 0, 0, 1, 1, 1, 1]
n_contributions: 21
n_punishments: 31
n_rounds: 24

output_dir: plots/simulation/ah_group_switching_punishment_50ep
figure_name: group_switching_punishment_50ep
basedir: .
pilot_data_file: experiments/2group_8agent_50ep.csv
pilot_experiment_name_map:
  ah_group_switching: pilot human manager
