artificial_humans:
  pseudo_group:
    contribution_model: artifacts/artificial_humans/pseudo_group/model/architecture_node+edge+rnn__dataset_full.pt
    valid_model: artifacts/artificial_humans/raven_script_22/model/rnn_False__dataset_full.pt
  group_switching:
    contribution_model: artifacts/artificial_humans/group_switching_contribution/model/architecture_node+edge+rnn__dataset_full.pt
    valid_model: artifacts/artificial_humans/raven_script_22/model/rnn_False__dataset_full.pt
    switch_model: artifacts/artificial_humans/switch_predictor/model/architecture_node+edge+rnn__dataset_full.pt
  pre_group:
    contribution_model: artifacts/artificial_humans/raven_script_21/model/architecture_node+edge+rnn__dataset_full.pt
    valid_model: artifacts/artificial_humans/raven_script_22/model/rnn_False__dataset_full.pt
managers:
  latest_manager:
    type: rl
    path: artifacts/manager/pr7/model/raven_per_group_manager.pt

n_episode_steps: 24
switch_every: 4
n_episodes: 100
n_groups: 2
n_agents: 8
agent_groups: [0, 0, 0, 0, 1, 1, 1, 1]
n_contributions: 21
n_punishments: 31
n_rounds: 24

output_dir: plots/simulation/ah_group_switching_comparison
figure_name: group_switching
basedir: .
