description: >-
  Train contribution predictor on new group switching data
  (8 agents, 2 groups).
exec:
  command: python -m aimanager train-ah {job_file}
  script_name: run_training
  data_dir: artifacts
  temp_dir: .log
  cores: 4
  memory: 8
params_only: true
params:
  fraction_training: 1.0
  seed: 38381
  mask_name: contribution_valid
  experiment_names: [ah_group_switching]
  labels:
    architecture: node+edge+rnn
    dataset: full
  n_contributions: 21
  n_punishments: 31
  n_cross_val: 10
  holdout_fold: 0
  n_player: 8
  n_groups: 2
  data_file: experiments/group_switching_human_human_group_switching_8_agents.csv
  model_name: graph
  shuffle_features: [prev_punishment, prev_contribution, contribution_valid]
  basedir: .
  output_dir: artifacts/artificial_humans/group_switching_contribution
  model_args:
    y_levels: 21
    y_name: contribution
    hidden_size: 5
    add_rnn: True
    add_edge_model: True
    add_global_model: False
    x_encoding:
      - name: prev_contribution
        n_levels: 21
        encoding: numeric
      - name: prev_punishment
        n_levels: 31
        encoding: numeric
      - name: agent_group
        n_levels: 2
        encoding: numeric
      - etype: bool
        name: prev_contribution_valid
  optimizer_args:
    lr: 3.e-4
    weight_decay: 1.e-5
  train_args:
    epochs: 10000
    batch_size: 4
    clamp_grad: 1
    eval_period: 50
    l1_entropy: 0
  device: cuda
  autoregression: False
