"""Emit the RL-manager training configs for the parameter-space-noise arm.

One arm of a four-way exploration comparison. Everything below except the
`param_noise` block and the seed is byte-identical to
`configs/training/rl_manager/rl_new_clones_s42.yml`: the same four artifacts,
the same opponent, the same env, the same common-pool reward, the same
hyperparameters, the same 4000 update steps and eval period 20 -- so the
episode budget matches the reference run exactly (4,000,000 behaviour episodes
plus 200,000 evaluation episodes; see notes/autoresearch_log/
rl-manager-param-noise.md and the `episode_budget` block of the probe JSON,
which counts them from the config rather than asserting them).

Five seeds, 42 to 46, the same five in every arm.

    python scripts/rl_param_noise/make_configs.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT_DIR = os.path.join(ROOT, "configs/training/rl_manager")

SEEDS = (42, 43, 44, 45, 46)

# Byte-identical to rl_new_clones_s42.yml. Read off that file, not guessed.
CONTRIBUTION_MODEL = (
    "artifacts/artificial_humans/"
    "group_switching_contribution_50ep_vnode_stimulus_skip_herding_copula/"
    "model/architecture_node+edge+rnn__dataset_50ep__epochs_575.pt"
)
SWITCH_MODEL = (
    "artifacts/artificial_humans/switch_joint_exodus/"
    "model/architecture_mlp+rnn+edge__dataset_50ep_doubled.pt"
)
OPPONENT_PUNISHER = (
    "artifacts/baselines/punishment_multinomial_ceiling_severity_copula.joblib"
)
VALID_MODEL = "artifacts/artificial_humans/raven_script_22/model/rnn_False__dataset_full.pt"  # noqa: E501
REWARD_MODE = "common_pool"

# The adaptation target, in punishment levels. Not a number at all: the
# sentinel `eps_matched` recomputes, every episode, the mean
# |a_behaviour - a_greedy| that epsilon-greedy at this config's own `eps`
# WOULD produce on that episode's states, and holds the weight noise there.
# That is what makes the arm one-variable -- the exploration becomes
# CONSISTENT, not smaller -- and it is Plappert's own rule, his DQN threshold
# being the distance an epsilon-greedy policy would have.
#
# It has to track rather than be fixed. The displacement epsilon-greedy
# injects depends on where the greedy action sits: 15.0 levels at action 0,
# 7.7 at action 15, so 1.50 and 0.77 punishment points at eps 0.1. Measured on
# the untrained stack it is 0.832 (probe.json); on the finished runs, whose
# policies sit near 0, it is about 1.5 -- the figure the brief quotes. A
# number frozen at initialisation would make this arm explore half as hard as
# the reference exactly when the reference explores hardest.
TARGET_DIVERGENCE = "eps_matched"

# The starting scale, measured: the smallest scale on the probe's sigma sweep
# whose mean greedy-action displacement already reaches the target (0.05 ->
# 0.975 against a target of 0.832), so the adaptation starts at its set point
# instead of walking there at 1% per episode.
INIT_SCALE = 0.05

TEMPLATE = """\
# AUTOGENERATED by scripts/rl_param_noise/make_configs.py -- do not hand-edit.
#
{banner}
#
# EXPLORATION ARM: parameter-space noise (Plappert et al., 2018).
# Every key below except `seed`, `job_id`, `output_dir` and the `param_noise`
# block is byte-identical to configs/training/rl_manager/rl_new_clones_s42.yml.
# The episode budget is therefore identical too: {n_update_steps} behaviour
# rollouts and {n_eval} evaluation rollouts of {batch_size} episodes each.

artificial_humans: {contribution_model}
artificial_humans_valid: {valid_model}
switch_model: {switch_model}
opponent_manager: {opponent_punisher}
artificial_humans_model: "graph"
job_id: {job_id}
seed: {seed}

manager_args:
  opt_args:
      lr: 2.e-4
  gamma: 0.98
  # Kept so the constructor's assertion still holds and so switching
  # `param_noise.enabled` to false reproduces the reference agent exactly.
  # With parameter noise on, the epsilon branch is never taken.
  eps: 0.1
  target_update_freq: 1000
{param_noise}
  model_args:
      hidden_size: 100
      add_rnn: true
      add_edge_model: true
      add_global_model: False
      x_encoding:
        - name: contribution
          n_levels: 21
          encoding: numeric
        - name: prev_punishment
          n_levels: 31
          encoding: numeric
        - etype: bool
          name: contribution_valid
        - etype: bool
          name: in_group
      b_encoding:
        - name: round_number
          n_levels: 32
          encoding: onehot

replay_memory_args:
  n_episodes: 100

n_update_steps: {n_update_steps}
eval_period: {eval_period}
training_batch_size: 1

env_args:
  n_groups: 2
  n_agents: 8
  agent_groups: [0, 0, 0, 0, 1, 1, 1, 1]
  rl_group_id: 0
  switch_every: 4
  n_contributions: 21
  n_punishments: 31
  n_rounds: 24
  batch_size: {batch_size}
  reward_mode: {reward_mode}

device: "cuda"
output_dir: "artifacts/manager/{job_id}"
basedir: "."
"""

PARAM_NOISE_BLOCK = """\
  param_noise:
      enabled: true
      # Additive Gaussian noise on the ACTING network's weights, redrawn once
      # per episode and held fixed for all 24 rounds of it. The policy net,
      # the target net and the opponent are never written to.
      scale: {init_scale}
      # Ordinal measure, in punishment levels: the mean displacement of the
      # greedy action. The unweighted softmax distance Plappert uses gives a
      # policy shifted one level (0.00445) and a policy with its contribution
      # contingency INVERTED (0.00469) the same number to within 5% on this
      # stack; `mad` separates them 1.00 against 5.77 (probe.json, section B).
      measure: mad
      # Tracks epsilon-greedy's own displacement episode by episode, using
      # the `eps` above. See make_configs.TARGET_DIVERGENCE.
      target: {target}
      adapt_coef: 1.01
      # Per-tensor RMS scaling, standing in for the paper's layer norm, which
      # cannot be added here without changing the network at zero noise.
      relative: true
"""

RUN_BANNER = """\
# Cleared to run. Pre-launch evidence in
# plots/data_analysis/evaluation/rl_manager_param_noise/:
#   * probe.json -- the measured epsilon-greedy displacement this target is
#     set to, the sigma sweep the starting scale is read off, the ordinal
#     divergence measurement, the untouched policy/target/opponent weights,
#     and the episode budget counted from this config;
#   * guard_gap.md -- the behaviour-versus-evaluated punishment gap and the
#     policy shape on a 200-step pilot, epsilon-greedy against this arm.
# See notes/autoresearch_log/rl-manager-param-noise.md."""

GUARD_BANNER = """\
# GUARD PILOT -- 200 update steps, not a result. Run in a matched pair
# (rl_pnoise_guard / rl_epsgreedy_guard, same seed, same everything else) to
# measure the behaviour-versus-evaluated punishment gap that this arm exists
# to shrink, and the policy shape on both sides of it. Do not read its policy
# as a finding: 200 steps is 5% of a run."""


def write(job_id, seed, n_update_steps, eval_period, banner, param_noise):
    batch_size = 1000
    text = TEMPLATE.format(
        banner=banner,
        job_id=job_id,
        contribution_model=CONTRIBUTION_MODEL,
        switch_model=SWITCH_MODEL,
        opponent_punisher=OPPONENT_PUNISHER,
        valid_model=VALID_MODEL,
        seed=seed,
        n_update_steps=n_update_steps,
        eval_period=eval_period,
        n_eval=len(range(0, n_update_steps, eval_period)),
        batch_size=batch_size,
        reward_mode=REWARD_MODE,
        param_noise=param_noise,
    )
    path = os.path.join(OUT_DIR, f"{job_id}.yml")
    with open(path, "w") as f:
        f.write(text)
    print(path)


def main():
    block = PARAM_NOISE_BLOCK.format(init_scale=INIT_SCALE, target=TARGET_DIVERGENCE)
    for seed in SEEDS:
        write(f"rl_pnoise_s{seed}", seed, 4000, 20, RUN_BANNER, block)
    write("rl_pnoise_guard", 42, 200, 10, GUARD_BANNER, block)
    # The paired reference: the same 200 steps with the mechanism switched
    # off, so the gap this arm reports is measured against its own stack and
    # not against a number quoted from another branch.
    write(
        "rl_epsgreedy_guard",
        42,
        200,
        10,
        GUARD_BANNER,
        "  param_noise:\n      enabled: false\n",
    )


if __name__ == "__main__":
    main()
