description: >-
  Investigating importance of different features.
exec:
  command: papermill -f {job_file} notebooks/artificial_humans/graph.ipynb {output_path}/graph.ipynb --cwd $(pwd)/notebooks/artificial_humans
  script_name: gpu
  data_dir: data
  temp_dir: temp
  cores: 4
  memory: 8
params_only: true
params:
  fraction_training: 1.0
  mask_name: recorded
  experiment_names: [trail_rounds_2]
  n_contributions: 21
  n_punishments: 31
  n_cross_val: 6
  n_player: 4
  data_file: ../../data/experiments/pilot_random1_player_round_slim.csv
  model_name: graph
  shuffle_features:
    - prev_punishments
    - contributions
    - prev_common_good
    - valid
    - prev_manager_valid
  model_args:
    y_levels: 31
    y_name: punishments
    hidden_size: 5
    add_rnn: False
    add_edge_model: True
    add_global_model: False
    x_encoding:
      - name: contributions
        n_levels: 21
        encoding: numeric
      - etype: bool
        name: valid
  optimizer_args:
    lr: 3.e-4
    weight_decay: 1.e-5
  train_args:
    epochs: 10000
    batch_size: 20
    clamp_grad: 1
    eval_period: 50
  device: cuda
grid:
  - labels.prev_punishments: [false, true]
    model_args.x_encoding.x:
      - null
      - name: prev_punishments
        n_levels: 31
        encoding: numeric
  - labels.prev_manager_valid: [false, true]
    model_args.x_encoding.x:
      - null
      - name: prev_manager_valid
        etype: bool
  - labels.round_n: [false, true]
    model_args.x_encoding.x:
      - null
      - name: round_number
        n_levels: 16
        encoding: numeric
