description: >-
  We test different architectures for the RL manager.
exec:
  command: python run.py run {job_file}
  script_name: gpu
  cores: 2
  memory: 16
  data_dir: data
  temp_dir: temp
params_only: true
params:
  __notebook__: notebooks/manager/rl_manager.ipynb
  artificial_humans: artifacts/artificial_humans/04_3_2_model/model/architecture_node+edge+rnn.pt
  artificial_humans_valid: artifacts/artificial_humans/02_4_valid/model/rnn_True.pt
  artificial_humans_model: graph
  manager_args:
    opt_args:
      lr: 3.e-4
    gamma: 1.0
    eps: 0.1
    target_update_freq: 1000
    model_args:
      hidden_size: 100
      add_rnn: true
      add_edge_model: true
      add_global_model: False
      x_encoding:
        - name: contribution
          n_levels: 21
          encoding: numeric
        - name: prev_punishment
          n_levels: 31
          encoding: numeric
        - etype: bool
          name: contribution_valid
        - etype: bool
          name: prev_contribution_valid
      b_encoding:
        - name: round_number
          n_levels: 16
          encoding: onehot
  replay_memory_args:
    n_episodes: 100
  n_update_steps: 20000
  eval_period: 20
  training_batch_size: 1
  env_args:
    n_agents: 4
    n_contributions: 21
    n_punishments: 31
    n_rounds: 16
    batch_size: 1000
  device: cuda
grid:
  - labels.architecture: [node, node+edge, node+rnn, node+edge+rnn]
    manager_args.model_args.add_rnn: [false, false, true, true]
    manager_args.model_args.add_edge_model: [false, true, false, true]
  - labels.run: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    seed: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
