"""Seed ensemble vs the contribution copula: is parameter (epistemic)
uncertainty a plausible source of the shared per-group error the copula
compensates for?

The PR #181 stimulus-skip contributor trunk is retrained K times with
different seeds (config `..._vnode_stimulus_skip_seed_ensemble.yml`), every
member is teacher-forced on the human canonical frame (the loaders of
`contribution_copula_rho.py`: one copy per game, rows where
`contribution_valid`), and the K predicted marginals per agent-round are
compared:

  (a) between-seed disagreement per agent-round -- SD over seeds of the
      expected contribution, and the mean total-variation distance between
      seed distributions -- against the predictive spread of one model;
  (b) the shared part: within every (episode, round, group) cell, the
      correlation across group members of the seed deviations
      (E_k - ensemble mean), pair-weighted over cells, per seed; the same on
      the PIT / latent scale the copula uses (each seed's expected value
      mapped through the ensemble-mean model's CDF, then Phi^-1); and the
      copula script's own estimator run on synthetic data generated by
      "one seed per episode" sampling with the ensemble-mean marginal --
      the rho the calibration would fit if the human data had been produced
      by the ensemble-as-noise model;
  (c) persistence of the cell-level seed deviation across rounds, against
      the copula's phi = 1 (static episode latent).

Alongside: the human residual within-group correlation given the ensemble
mean (PR #140's decomposition, recomputed), and the copula rho refit on the
human data with the ensemble-mean marginal.

Measurement only; imports graph.py, so it needs torch_geometric (Raven):
    python scripts/data_analysis/copula_seed_ensemble.py \
        [--ensemble-dir DIR] [--shipped PT] [--out-dir DIR] [--n-syn 20]
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path

os.environ.setdefault("DISABLE_PANDERA_IMPORT_WARNING", "True")
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from scipy.special import ndtri  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
for sub in ("src", "scripts/artificial_humans", "scripts/baselines"):
    sys.path.insert(0, str(ROOT / sub))

import contribution_copula_rho as cc  # noqa: E402
import punishment_copula_rho as pc  # noqa: E402

from aimanager.generic.graph import GraphNetwork  # noqa: E402

AH = "artifacts/artificial_humans"
ENSEMBLE_DIR = (
    f"{AH}/group_switching_contribution_50ep_vnode_stimulus_skip_seed_ensemble"
)
SHIPPED = (
    f"{AH}/group_switching_contribution_50ep_vnode_stimulus_skip/model/"
    "architecture_node+edge+rnn__dataset_50ep__epochs_575.pt"
)
COPULA_PARAMS = (
    f"{AH}/group_switching_contribution_50ep_vnode_stimulus_skip_herding_copula/"
    "calibration/copula_params.json"
)
OUT_DIR = "plots/data_analysis/copula_seed_ensemble"
N_BOOT = 200
QS = [0.1, 0.25, 0.5, 0.75, 0.9, 0.99]
f = pc.f


# --------------------------------------------------------------------------- #
# predictions
# --------------------------------------------------------------------------- #
def load_members(ens_dir, shipped):
    pts = sorted(Path(ens_dir, "model").glob("*seed_*.pt"))
    assert pts, f"no seed artifacts under {ens_dir}/model"
    members = {}
    for p in pts:
        seed = int(p.stem.split("seed_")[-1])
        m = GraphNetwork.load(str(p), device="cpu")
        m.eval()
        assert m.y_name == "contribution" and m.copula_rho == 0.0
        members[f"seed_{seed}"] = m
    ship = GraphNetwork.load(str(shipped), device="cpu")
    ship.eval()
    assert ship.copula_rho == 0.0, "pass the bare trunk, not the copula stamp"
    return members, ship


def predict_stack(models, data, idx):
    """Teacher-forced marginals of every model on the same rows: P [K, n, L]
    plus the row index (identical for every model -- it is the mask's)."""
    ref = None
    P = []
    for name, m in models.items():
        rows = cc.teacher_forced_rows(m, data, idx)
        if ref is None:
            ref = rows
        else:
            for k in ("y", "cell", "episode", "agent", "round", "group"):
                assert np.array_equal(ref[k], rows[k]), f"{name}: row mismatch on {k}"
        P.append(rows["P"])
    return np.stack(P), ref


def pit_latent(Pbar, x):
    """Phi^-1 of the ensemble-mean model's CDF, made continuous by a
    piecewise-linear interpolation inside each level's cell [a-.5, a+.5],
    evaluated at the continuous expected values x [.., n]."""
    n_lev = Pbar.shape[1]
    cdf = np.cumsum(Pbar, axis=1)
    lo = cdf - Pbar  # F(a - 1)
    a = np.clip(np.rint(x), 0, n_lev - 1).astype(np.int64)
    rows = np.arange(Pbar.shape[0])
    frac = np.clip(x - a + 0.5, 0.0, 1.0)
    u = lo[rows, a] + frac * Pbar[rows, a]
    return ndtri(np.clip(u, pc.U_EPS, 1.0 - pc.U_EPS))


# --------------------------------------------------------------------------- #
# within-cell correlation of a column stack, with an episode-cluster bootstrap
# --------------------------------------------------------------------------- #
def within_cell_corr(Z, cell):
    """Pair-weighted within-cell correlation per column of Z [n, R]
    (pc.rho_pairs) and the per-cell-weighted version (pc.rho_cells)."""
    order, starts, sizes = pc.blocks(cell)
    Zo = Z[order]
    r_pairs, n_pairs = pc.rho_pairs(Zo, starts, sizes)
    r_cells = pc.rho_cells(Zo, starts, sizes)
    return r_pairs, r_cells, n_pairs


def boot_within_cell_corr(Z, cell, episode, n_boot, seed):
    """Episode-cluster bootstrap of the pair-weighted within-cell correlation
    (mean over columns). An episode drawn twice gets distinct cell ids."""
    per_ep = {int(e): np.flatnonzero(episode == e) for e in np.unique(episode)}
    ep_ids = np.array(sorted(per_ep))
    n_cell = int(cell.max()) + 1
    rng = np.random.default_rng(seed)
    out = np.empty(n_boot)
    for b in range(n_boot):
        draw = rng.choice(ep_ids, size=len(ep_ids), replace=True)
        rows = np.concatenate([per_ep[int(e)] for e in draw])
        copy = np.repeat(np.arange(len(draw)), [len(per_ep[int(e)]) for e in draw])
        c = cell[rows] + copy * n_cell
        out[b] = within_cell_corr(Z[rows], c)[0].mean()
    return out


def ci(x):
    return [float(np.percentile(x, 2.5)), float(np.percentile(x, 97.5))]


# --------------------------------------------------------------------------- #
# persistence of the cell-level seed deviation
# --------------------------------------------------------------------------- #
def cell_means(d, rows):
    """Mean seed deviation per (episode, round, group) cell: frame with one
    row per cell and one column per seed."""
    df = pd.DataFrame(d, columns=[f"s{k}" for k in range(d.shape[1])])
    for k in ("episode", "round", "group"):
        df[k] = rows[k]
    return df.groupby(["episode", "round", "group"]).mean().reset_index()


def lag_corr(cm, lag):
    """Pooled-over-seeds correlation of the cell deviation at round r with the
    same (episode, group) cell at round r + lag."""
    seeds = [c for c in cm.columns if c.startswith("s")]
    a = cm.copy()
    b = cm.copy()
    b["round"] = b["round"] - lag
    m = a.merge(b, on=["episode", "round", "group"], suffixes=("", "_next"))
    x = np.concatenate([m[s].to_numpy() for s in seeds])
    y = np.concatenate([m[f"{s}_next"].to_numpy() for s in seeds])
    return float(np.corrcoef(x, y)[0, 1]), int(len(m))


def episode_icc(cm):
    """Share of the cell-deviation variance carried by the (episode, group)
    level, pooled over seeds: ICC(1) of D over rounds within (episode, group)."""
    seeds = [c for c in cm.columns if c.startswith("s")]
    key = (cm["episode"] * 2 + cm["group"]).to_numpy()
    order, starts, sizes = pc.blocks(key)
    Z = cm[seeds].to_numpy()[order]
    return float(pc.icc_oneway(Z, starts, sizes).mean())


def cross_player_lag1(d, rows):
    """The copula script's lag-1 pairing on the seed deviations: corr of
    d_i(r) with d_j(r + 1), same (episode, group), pooled over seeds; split
    into different-participant (the copula's PRIMARY) and same-participant."""
    ic, jc = cc.cross_pairs(rows, 1)
    is_self = rows["agent"][ic] == rows["agent"][jc]
    out = {}
    for name, sel in (("cross_player", ~is_self), ("self", is_self)):
        x = d[ic[sel]].reshape(-1)
        y = d[jc[sel]].reshape(-1)
        out[name] = (float(np.corrcoef(x, y)[0, 1]), int(sel.sum()))
    return out


# --------------------------------------------------------------------------- #
def synthetic_rho(P, Pbar, cell, episode, n_rep, seed):
    """The copula calibration run on data the ensemble-as-noise model would
    produce: one seed per episode, every agent-round drawn independently from
    that seed's marginal, then the pairwise MLE with the ensemble-mean
    marginal as the model. Returns the rho per replicate."""
    K, n, L = P.shape
    rng = np.random.default_rng(seed)
    eps = np.unique(episode)
    out = []
    for _ in range(n_rep):
        k_of_ep = dict(zip(eps.tolist(), rng.integers(0, K, len(eps))))
        k = np.array([k_of_ep[int(e)] for e in episode])
        Pk = P[k, np.arange(n)]
        u = rng.random(n)
        y = (np.cumsum(Pk, axis=1) < u[:, None]).sum(1).clip(0, L - 1)
        out.append(pc.mle_on_rows(Pbar, y, cell)[0])
    return np.array(out)


def quantile_row(name, x):
    row = {"quantity": name, "mean": float(x.mean()), "max": float(x.max())}
    row.update({f"q{int(q * 100)}": float(np.quantile(x, q)) for q in QS})
    return row


def analyse(label, members, ship, data, idx, copula, n_syn, out_dir):
    t0 = time.time()
    print(f"\n{'=' * 78}\n{label}: {len(idx)} episodes\n{'=' * 78}")
    P, rows = predict_stack(members, data, idx)
    P_ship = predict_stack({"shipped": ship}, data, idx)[0][0]
    K, n, L = P.shape
    names = list(members)
    y, cell, episode = rows["y"], rows["cell"], rows["episode"]
    lev = np.arange(L, dtype=np.float64)
    _, _, sizes = pc.blocks(cell)
    print(f"members={names} rows={n} cells>=2={(sizes >= 2).sum()}")

    # ---- fit quality per member (context) ----
    nll = {
        nm: float(-np.log(P[k, np.arange(n), y]).mean()) for k, nm in enumerate(names)
    }
    Pbar = P.mean(0)
    nll["ensemble_mean"] = float(-np.log(Pbar[np.arange(n), y]).mean())
    nll["shipped"] = float(-np.log(P_ship[np.arange(n), y]).mean())
    print("teacher-forced NLL:", {k: round(v, 4) for k, v in nll.items()})

    # ---- (a) between-seed disagreement per agent-round ----
    E = P @ lev  # [K, n]
    E_bar = E.mean(0)
    E_ship = P_ship @ lev
    sd_E = E.std(0, ddof=1)
    var_pred_bar = (Pbar * lev**2).sum(1) - E_bar**2
    sd_pred_bar = np.sqrt(np.clip(var_pred_bar, 0, None))
    sd_pred_seed = np.sqrt(np.clip(((P * lev**2).sum(2) - E**2), 0, None)).mean(0)
    tv = np.zeros(n)
    n_pairs_k = 0
    for a in range(K):
        for b in range(a + 1, K):
            tv += 0.5 * np.abs(P[a] - P[b]).sum(1)
            n_pairs_k += 1
    tv /= n_pairs_k
    tv_ship = np.mean([0.5 * np.abs(P[a] - P_ship).sum(1) for a in range(K)], axis=0)
    resid_bar = y - E_bar
    dis = pd.DataFrame(
        [
            quantile_row("sd_E_between_seeds", sd_E),
            quantile_row("tv_between_seeds", tv),
            quantile_row("sd_pred_ensemble_mean", sd_pred_bar),
            quantile_row("sd_pred_single_seed_mean", sd_pred_seed),
            quantile_row("abs_resid_human_vs_ensemble_mean", np.abs(resid_bar)),
            quantile_row("abs_E_shipped_minus_E_bar", np.abs(E_ship - E_bar)),
            quantile_row("tv_shipped_vs_seeds", tv_ship),
        ]
    )
    print("\n(a) between-seed disagreement per agent-round (contribution units)")
    print(dis.to_string(index=False, float_format=lambda v: f"{v:.4f}"))
    ratio_sd = float(sd_E.mean() / sd_pred_bar.mean())
    ratio_var = float((sd_E**2).mean() / var_pred_bar.mean())
    ratio_resid = float((sd_E**2).mean() / (resid_bar**2).mean())
    print(
        f"mean sd_E / mean sd_pred = {ratio_sd:.4f}; "
        f"mean var_E / mean var_pred = {ratio_var:.4f}; "
        f"mean var_E / mean resid^2 = {ratio_resid:.4f}"
    )

    # ---- (b) the shared part ----
    d = (E - E_bar).T  # [n, K] seed deviations of the expected value
    r_pairs, r_cells, n_pairs = within_cell_corr(d, cell)
    boot_raw = boot_within_cell_corr(d, cell, episode, N_BOOT, pc.SEED)
    z = pit_latent(Pbar, E).T  # [n, K] seeds' expected values on the latent scale
    dz = z - z.mean(1, keepdims=True)
    v_lat = float((z.var(1, ddof=1)).mean())
    rz_pairs, rz_cells, _ = within_cell_corr(dz, cell)
    boot_z = boot_within_cell_corr(dz, cell, episode, N_BOOT, pc.SEED)
    implied = float(rz_pairs.mean() * v_lat / (1.0 + v_lat))
    implied_boot = boot_z * v_lat / (1.0 + v_lat)
    print(
        "\n(b) shared part: within-(episode, round, group) correlation of seed deviations"
    )
    print(f"  pairs={n_pairs}")
    print(f"  E scale, per seed (pair-weighted): {np.round(r_pairs, 4).tolist()}")
    print(
        f"  E scale mean {f(r_pairs.mean())}  95% CI {ci(boot_raw)}  per-cell-weighted mean {f(r_cells.mean())}"
    )
    print(f"  latent scale per seed: {np.round(rz_pairs, 4).tolist()}")
    print(
        f"  latent scale mean {f(rz_pairs.mean())}  95% CI {ci(boot_z)}  per-cell-weighted {f(rz_cells.mean())}"
    )
    print(f"  between-seed variance on the latent scale v = {f(v_lat)}")
    print(
        f"  implied copula rho = corr * v / (1 + v) = {f(implied)}  "
        f"95% CI {ci(implied_boot)}  (INFERRED: additive latent shift model)"
    )

    # the copula script's own estimator on ensemble-as-noise synthetic data
    t_syn = time.time()
    rho_syn = synthetic_rho(P, Pbar, cell, episode, n_syn, pc.SEED)
    rho_null = synthetic_rho(Pbar[None], Pbar, cell, episode, 3, pc.SEED + 1)
    print(
        f"  copula MLE on 'one seed per episode' synthetic data ({n_syn} reps): "
        f"mean {f(rho_syn.mean())} sd {f(rho_syn.std(ddof=1))} "
        f"min/max {f(rho_syn.min())}/{f(rho_syn.max())}  [{time.time() - t_syn:.0f}s]"
    )
    print(
        f"  same estimator on independent draws from the ensemble mean (null, 3 reps): "
        f"{np.round(rho_null, 4).tolist()}"
    )

    # the copula rho refit on the human data with the ensemble-mean marginal
    t_h = time.time()
    rho_bar, npr, _, _ = pc.mle_on_rows(Pbar, y, cell)
    boot_bar = pc.bootstrap_mle(Pbar, y, cell, episode, N_BOOT, pc.SEED, rho_bar)
    rho_ship = pc.mle_on_rows(P_ship, y, cell)[0]
    rho_seed = [pc.mle_on_rows(P[k], y, cell)[0] for k in range(K)]
    print(
        f"  copula rho, human data, ensemble-mean marginal: {f(rho_bar)} "
        f"95% CI {ci(boot_bar)}; shipped marginal {f(rho_ship)} "
        f"(calibration JSON: {f(copula['rho'])} CI {copula['rho_ci']}); "
        f"per seed {np.round(rho_seed, 4).tolist()}  [{time.time() - t_h:.0f}s]"
    )

    # human residual within-group correlation given the model (PR #140)
    resid_ship = y - E_ship
    r_raw = within_cell_corr(y[:, None].astype(float), cell)[0][0]
    r_res_bar = within_cell_corr(resid_bar[:, None], cell)[0][0]
    r_res_ship = within_cell_corr(resid_ship[:, None], cell)[0][0]
    boot_res = boot_within_cell_corr(resid_bar[:, None], cell, episode, N_BOOT, pc.SEED)
    print(
        f"  human within-group correlation: raw {f(r_raw)}; residual given "
        f"ensemble mean {f(r_res_bar)} 95% CI {ci(boot_res)}; given shipped {f(r_res_ship)}"
    )

    # ---- (c) persistence ----
    cm = cell_means(d, rows)
    lags = {lag: lag_corr(cm, lag) for lag in (1, 2, 3, 5, 10)}
    icc = episode_icc(cm)
    xl = cross_player_lag1(d, rows)
    within_round = float(r_pairs.mean())
    phi_like = (
        xl["cross_player"][0] / within_round if within_round > 0 else float("nan")
    )
    print("\n(c) persistence of the cell-mean seed deviation across rounds")
    for lag, (r, m) in lags.items():
        print(f"  lag {lag:>2}: corr {r:.4f}  (cell pairs {m})")
    print(f"  ICC of the cell deviation over rounds within (episode, group): {icc:.4f}")
    print(
        f"  agent-level lag-1 corr, different participants {xl['cross_player'][0]:.4f} "
        f"(n {xl['cross_player'][1]}), same participant {xl['self'][0]:.4f}; "
        f"phi analogue = cross-player lag-1 / within-round = {phi_like:.4f} "
        f"(copula: phi_hat {f(copula['phi'])}, shipped phi {copula['phi_final']})"
    )

    summary = dict(
        label=label,
        n_episodes=int(len(idx)),
        n_rows=int(n),
        n_pairs=int(n_pairs),
        members=names,
        nll=nll,
        ratio_sd_E_to_sd_pred=ratio_sd,
        ratio_var_E_to_var_pred=ratio_var,
        ratio_var_E_to_resid_sq=ratio_resid,
        corr_E_per_seed=r_pairs.tolist(),
        corr_E_mean=float(r_pairs.mean()),
        corr_E_ci=ci(boot_raw),
        corr_E_cellweighted=float(r_cells.mean()),
        corr_latent_per_seed=rz_pairs.tolist(),
        corr_latent_mean=float(rz_pairs.mean()),
        corr_latent_ci=ci(boot_z),
        latent_between_seed_var=v_lat,
        implied_rho=implied,
        implied_rho_ci=ci(implied_boot),
        rho_synthetic_mean=float(rho_syn.mean()),
        rho_synthetic_sd=float(rho_syn.std(ddof=1)),
        rho_synthetic_reps=rho_syn.tolist(),
        rho_null_reps=rho_null.tolist(),
        rho_human_ensemble_mean=float(rho_bar),
        rho_human_ensemble_mean_ci=ci(boot_bar),
        rho_human_shipped=float(rho_ship),
        rho_human_per_seed=[float(r) for r in rho_seed],
        rho_copula_json=copula["rho"],
        rho_copula_json_ci=copula["rho_ci"],
        human_corr_raw=float(r_raw),
        human_resid_corr_ensemble_mean=float(r_res_bar),
        human_resid_corr_ensemble_mean_ci=ci(boot_res),
        human_resid_corr_shipped=float(r_res_ship),
        persistence_lag_corr={str(k): v[0] for k, v in lags.items()},
        persistence_icc_episode=icc,
        lag1_cross_player=xl["cross_player"][0],
        lag1_self=xl["self"][0],
        phi_analogue=float(phi_like),
        seconds=time.time() - t0,
    )
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    dis.to_csv(out_dir / f"{label}_disagreement.csv", index=False)
    per_row = pd.DataFrame(
        {
            "episode": episode,
            "agent": rows["agent"],
            "round": rows["round"],
            "group": rows["group"],
            "y": y,
            "E_bar": E_bar,
            "E_shipped": E_ship,
            "sd_E": sd_E,
            "tv": tv,
            "sd_pred_bar": sd_pred_bar,
            **{f"E_{nm}": E[k] for k, nm in enumerate(names)},
            **{f"z_{nm}": z[:, k] for k, nm in enumerate(names)},
        }
    )
    per_row.to_parquet(out_dir / f"{label}_per_row.parquet", index=False)
    (out_dir / f"{label}_summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    print(f"\nwrote {cc.rel(out_dir)}/{label}_*  [{summary['seconds']:.0f}s]")
    return summary


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ensemble-dir", default=str(ROOT / ENSEMBLE_DIR))
    ap.add_argument("--shipped", default=str(ROOT / SHIPPED))
    ap.add_argument("--copula-params", default=str(ROOT / COPULA_PARAMS))
    ap.add_argument("--out-dir", default=str(ROOT / OUT_DIR))
    ap.add_argument("--n-syn", type=int, default=20)
    args = ap.parse_args()

    copula = json.loads(Path(args.copula_params).read_text())
    members, ship = load_members(args.ensemble_dir, args.shipped)
    data, pair_id, key_to_idx, _ = cc.load_full()
    tr = cc.select_split(key_to_idx, cc.TRAIN, cc.N_TRAIN_EP)
    te = cc.select_split(key_to_idx, cc.TEST, cc.N_TEST_EP)
    canon = np.array(sorted(set(tr.tolist()) | set(te.tolist())))
    print(f"members: {list(members)}; shipped: {cc.rel(args.shipped)}")
    print(
        f"copula calibration: rho {copula['rho']} CI {copula['rho_ci']} phi {copula['phi_final']}"
    )

    analyse("train40", members, ship, data, tr, copula, args.n_syn, args.out_dir)
    analyse("canon50", members, ship, data, canon, copula, args.n_syn, args.out_dir)


if __name__ == "__main__":
    main()
