y_encoding: onehot
n_contributions: 21
n_punishments: 31
n_cross_val: 2
fraction_training: 1.0
data: ../data/pilot_random1_player_round_slim.csv
output_path: ../data/dev
labels: {}
model_args:
  n_layers: 2
  hidden_size: 40
optimizer_args:
  lr: 1.e-4
  weight_decay: 1.e-5
train_args:
  epochs: 100
  batch_size: 40
  clamp_grad: 1
  eval_period: 10
device: cpu
