description: >-
  Scan of target update and replay memory.
exec:
  command: papermill -f {job_file} notebooks/manager/rl_manager_v3.ipynb {output_path}/rl_manager_v3.ipynb --cwd $(pwd)/notebooks/manager
  script_name: gpu
  cores: 2
  memory: 16
  data_dir: data
  temp_dir: temp
params_only: true
params:
  artificial_humans: "../../data/artificial_humans/01_rnn_edge_features/model/rnn_True__edge_True__global_features_False.pt"
  artificial_humans_model: graph
  manager_args:
    opt_args:
      lr: 3.e-4
    gamma: 1.0
    eps: 0.1
    target_update_freq: 200
    model_args:
      hidden_size: 40
      add_rnn: true
      add_edge_model: true
      add_global_model: False
      x_encoding:
        - name: contributions
          n_levels: 21
          encoding: numeric
        - name: prev_punishments
          n_levels: 31
          encoding: numeric
      u_encoding:
        - name: round_number
          n_levels: 16
          encoding: numeric
        - name: prev_common_good
          norm: 128
          etype: float
      b_encoding:
        - name: round_number
          n_levels: 16
          encoding: onehot
  replay_memory_args:
    n_episodes: 200
  n_update_steps: 20000
  eval_period: 20
  env_args:
    n_agents: 4
    n_contributions: 21
    n_punishments: 31
    n_rounds: 16
    batch_size: 1000
  device: cuda
grid:
  - labels.target_update_freq: [10, 100, 1000]
    manager_args.target_update_freq: [10, 100, 1000]
  - labels.replay_memory: [10, 100, 1000]
    replay_memory_args.n_episodes: [10, 100, 1000]
  - labels.run: [0,1,2,3,4,5,6,7,8,9]
