artificial_humans:
  full:
    contribution_model: artifacts/behavioral_cloning/21_contribution_model_v4/model/architecture_node+edge+rnn__dataset_full.pt
    valid_model: artifacts/behavioral_cloning/22_contribution_valid_model_v4/model/rnn_False__dataset_full.pt

managers:
  after_pr7:
    type: rl
    path: artifacts/manager/pr7/model/raven_per_group_manager.pt
  02_1group:
    type: rl
    path: artifacts/manager/02_rnn_node_1group/model/02_rnn_node_1group_manager.pt
  zero_punishment:
    type: dummy

n_episode_steps: 24
n_episodes: 100
n_groups: 1
n_agents: 4
n_contributions: 21
n_punishments: 31
n_rounds: 24

output_dir: plots/simulation/05_pr7_02_vs_dummy
figure_name: pr7_02_vs_dummy
basedir: .
