#!/usr/bin/env bash
#
# What separates the arm from its control, mechanically. Diffs the whole
# config below the header comment block, so anything that shows up and is not
# job_id, output_dir or an exploration key is a contract violation.
#
#   scripts/rl_anneal_local/config_diff.sh > \
#       plots/data_analysis/rl_anneal_local/config_diff.txt
#
set -uo pipefail
cd "$(dirname "$0")/../.."
C=configs/training/rl_manager

body() { sed '1,/^$/d' "$1"; }

echo "# Arm against its control, seed 42. Generated by"
echo "# scripts/rl_anneal_local/config_diff.sh; header comments stripped."
echo
diff <(body "$C/rl_new_clones_s42.yml") <(body "$C/rl_anneal_local_s42.yml")
echo
echo "# The control's two new seeds against a finished one."
echo
diff <(body "$C/rl_new_clones_s42.yml") <(body "$C/rl_new_clones_s45.yml")
