"""Emit the training configs for the annealed, local epsilon-greedy arm.

One arm of a four-way exploration comparison. Everything outside
`manager_args` is copied verbatim from
configs/training/rl_manager/rl_new_clones_s42.yml -- the same four artifacts,
the same opponent, the same env, the same common-pool reward, the same 4000
update steps -- so the only difference between this arm and its control is the
behaviour policy. The five seeds are the same five in every arm so seed
effects cancel in the paired comparison.

Three keys are added to `manager_args`, all defaulting to off in code
(src/aimanager/manager/exploration.py), so the unmodified behaviour is
recoverable from config alone:

  eps_final / eps_anneal_steps
      Linear decay of eps from 0.1 to 0.01, reaching the floor at step 3000 of
      4000 and holding it for the last quarter of training. Linear-to-a-floor
      is the DQN standard and the only common schedule that reaches its floor
      at a stated step rather than asymptotically, so "the behaviour policy
      has converged onto the evaluated one" is checkable rather than asserted.

  explore_sigma
      The exploratory action is drawn from a discretised Gaussian centred on
      the greedy action with sigma = 2, truncated to [0, 30] and renormalised,
      instead of uniformly over all 31 levels. sigma = 2 probes one to two
      punishment points around the current policy -- the scale of the learned
      signal -- rather than the whole 30-point range.

    python scripts/rl_anneal_local/make_configs.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT_DIR = os.path.join(ROOT, "configs/training/rl_manager")

SEEDS = (42, 43, 44, 45, 46)

N_UPDATE_STEPS = 4000
EVAL_PERIOD = 20
# 75% of training: the behaviour policy is at its floor for the final quarter,
# so the policy that is saved was trained on data drawn from (almost) itself.
ANNEAL_FRACTION = 0.75
EPS_START = 0.1
EPS_FINAL = 0.01
EXPLORE_SIGMA = 2.0

# Short enough to price in under half an hour, long enough that the anneal
# completes inside it -- the guard measures the behaviour-versus-evaluated gap
# at the first and last evaluation, and a pilot whose epsilon never moves
# would show nothing.
PILOT_STEPS = 300

# Byte-identical to the corresponding block of rl_new_clones_s42.yml.
CONTRIBUTION_MODEL = (
    "artifacts/artificial_humans/"
    "group_switching_contribution_50ep_vnode_stimulus_skip_herding_copula/"
    "model/architecture_node+edge+rnn__dataset_50ep__epochs_575.pt"
)
SWITCH_MODEL = (
    "artifacts/artificial_humans/switch_joint_exodus/"
    "model/architecture_mlp+rnn+edge__dataset_50ep_doubled.pt"
)
OPPONENT_PUNISHER = (
    "artifacts/baselines/punishment_multinomial_ceiling_severity_copula.joblib"
)
VALID_MODEL = "artifacts/artificial_humans/raven_script_22/model/rnn_False__dataset_full.pt"  # noqa: E501
REWARD_MODE = "common_pool"

ARM_BANNER = """\
# Arm: ANNEALED, LOCAL epsilon-greedy. One of four exploration arms; the
# control is configs/training/rl_manager/rl_new_clones_s{seed}.yml, which is
# this file with the three exploration keys removed. Nothing else differs:
# same artifacts, same opponent, same env, same reward, same 4000 update
# steps, same five seeds (42-46). See
# notes/autoresearch_log/rl-manager-annealed-local.md."""

PILOT_BANNER = """\
# GUARD PILOT -- not a result. {steps} update steps, run only to show the
# behaviour-versus-evaluated punishment gap at the start and at the end of an
# anneal, and the policy shape the two rollouts produce. Do not read its
# policy as an outcome; {steps} steps is 7.5% of a real run."""

TEMPLATE = """\
# AUTOGENERATED by scripts/rl_anneal_local/make_configs.py -- do not hand-edit.
#
{banner}
#
# RL manager vs the current corrected clones ({job_id}).
# Every key below except `seed`, `job_id` and `output_dir` is byte-identical
# across the five runs.

artificial_humans: {contribution_model}
artificial_humans_valid: {valid_model}
switch_model: {switch_model}
opponent_manager: {opponent_punisher}
artificial_humans_model: "graph"
job_id: {job_id}
seed: {seed}

manager_args:
  opt_args:
      lr: 2.e-4
  gamma: 0.98
  eps: {eps_start}
{exploration_keys}\
  target_update_freq: 1000
  model_args:
      hidden_size: 100
      add_rnn: true
      add_edge_model: true
      add_global_model: False
      x_encoding:
        - name: contribution
          n_levels: 21
          encoding: numeric
        - name: prev_punishment
          n_levels: 31
          encoding: numeric
        - etype: bool
          name: contribution_valid
        - etype: bool
          name: in_group
      b_encoding:
        - name: round_number
          n_levels: 32
          encoding: onehot

replay_memory_args:
  n_episodes: 100

n_update_steps: {n_update_steps}
eval_period: {eval_period}
training_batch_size: 1

env_args:
  n_groups: 2
  n_agents: 8
  agent_groups: [0, 0, 0, 0, 1, 1, 1, 1]
  rl_group_id: 0
  switch_every: 4
  n_contributions: 21
  n_punishments: 31
  n_rounds: 24
  batch_size: 1000
  reward_mode: {reward_mode}

device: "cuda"
output_dir: "artifacts/manager/{job_id}"
basedir: "."
"""


def exploration_block(n_update_steps, annealed_local):
    if not annealed_local:
        # The control arm: no keys at all, which is the unmodified
        # constant-eps, uniform-proposal behaviour.
        return ""
    steps = int(round(ANNEAL_FRACTION * n_update_steps))
    return (
        f"  eps_final: {EPS_FINAL}\n"
        f"  eps_anneal_steps: {steps}\n"
        f"  explore_sigma: {EXPLORE_SIGMA}\n"
    )


def write(job_id, seed, n_update_steps, eval_period, banner, annealed_local=True):
    text = TEMPLATE.format(
        banner=banner,
        job_id=job_id,
        contribution_model=CONTRIBUTION_MODEL,
        switch_model=SWITCH_MODEL,
        opponent_punisher=OPPONENT_PUNISHER,
        valid_model=VALID_MODEL,
        seed=seed,
        eps_start=EPS_START,
        exploration_keys=exploration_block(n_update_steps, annealed_local),
        n_update_steps=n_update_steps,
        eval_period=eval_period,
        reward_mode=REWARD_MODE,
    )
    path = os.path.join(OUT_DIR, f"{job_id}.yml")
    with open(path, "w") as f:
        f.write(text)
    print(path)


def main():
    for seed in SEEDS:
        write(
            f"rl_anneal_local_s{seed}",
            seed,
            N_UPDATE_STEPS,
            EVAL_PERIOD,
            ARM_BANNER.format(seed=seed),
        )
    # The two pilots differ only in the exploration keys, which is what makes
    # the guard a contrast rather than a single number.
    write(
        "rl_anneal_local_pilot",
        42,
        PILOT_STEPS,
        EVAL_PERIOD,
        PILOT_BANNER.format(steps=PILOT_STEPS),
    )
    write(
        "rl_anneal_control_pilot",
        42,
        PILOT_STEPS,
        EVAL_PERIOD,
        PILOT_BANNER.format(steps=PILOT_STEPS),
        annealed_local=False,
    )


if __name__ == "__main__":
    main()
