"""Emit the RL-manager training configs for the bootstrapped-DQN arm.

One arm of a four-way exploration comparison. Every key except `seed`,
`job_id`, `output_dir` and the four `manager_args` keys that define the
mechanism is byte-identical to
`configs/training/rl_manager/rl_new_clones_s42.yml` at 0ff44a9, so the
comparison is against one variable.

    python scripts/rl_bootstrapped/make_configs.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT_DIR = os.path.join(ROOT, "configs/training/rl_manager")

SEEDS = (42, 43, 44, 45, 46)

# Byte-identical to rl_new_clones_s42.yml. Do not touch: one variable at a
# time, and the variable is the exploration mechanism.
CONTRIBUTION_MODEL = (
    "artifacts/artificial_humans/"
    "group_switching_contribution_50ep_vnode_stimulus_skip_herding_copula/"
    "model/architecture_node+edge+rnn__dataset_50ep__epochs_575.pt"
)
SWITCH_MODEL = (
    "artifacts/artificial_humans/switch_joint_exodus/"
    "model/architecture_mlp+rnn+edge__dataset_50ep_doubled.pt"
)
OPPONENT_PUNISHER = (
    "artifacts/baselines/punishment_multinomial_ceiling_severity_copula.joblib"
)
VALID_MODEL = "artifacts/artificial_humans/raven_script_22/model/rnn_False__dataset_full.pt"  # noqa: E501

# K, chosen from the pilot measurement recorded in
# notes/autoresearch_log/rl-manager-bootstrapped-dqn.md, not from convention.
#
# The binding constraint turned out to be ensemble survival, not cost, and it
# is monotone in K over the range tested. On 200-step pilots (seed 42, one
# variable): at K=4 the ensemble is dead by update step 10 -- head
# disagreement 0.000, action spread 0.0, punishment exactly 0 under both the
# behaviour and the evaluated policy. At K=10 it survives, disagreement 1.000
# and spread 2.0 at step 190. At K=20 it survives wider, spread 3.0, and it is
# the ONLY bootstrap configuration whose evaluated policy still punishes at
# all (2.63 against 0.00 at K=4 and K=10) -- a consensus pinned at zero cannot
# express a policy shape, which is this comparison's outcome measure.
#
# Cost does not constrain the choice: 5.56 / 5.72 / 6.89 / 5.84 s per update
# step at K = 1 / 4 / 10 / 20. Not monotone -- the K=10 job drew a slower node
# -- so within node-to-node noise K is free up to 20. The head is 31*K outputs
# off a 100-wide readout, negligible beside the artificial humans' forward
# passes.
N_HEADS = 20
BOOTSTRAP_P = 0.5

TEMPLATE = """\
# AUTOGENERATED by scripts/rl_bootstrapped/make_configs.py -- do not hand-edit.
#
{banner}
#
# Bootstrapped-DQN arm of the exploration comparison ({job_id}).
# Identical to configs/training/rl_manager/rl_new_clones_s42.yml at 0ff44a9
# except for `seed`, `job_id`, `output_dir` and the four manager_args keys
# below that define the mechanism. `eps` is retained at its historical value
# and is UNUSED: under `exploration: bootstrap` the behaviour policy is a
# head's own greedy policy and there is no per-action dithering at all.

artificial_humans: {contribution_model}
artificial_humans_valid: {valid_model}
switch_model: {switch_model}
opponent_manager: {opponent_punisher}
artificial_humans_model: "graph"
job_id: {job_id}
seed: {seed}

manager_args:
  opt_args:
      lr: 2.e-4
  gamma: 0.98
  eps: 0.1
  target_update_freq: 1000
  exploration: {exploration}
  n_heads: {n_heads}
  bootstrap_p: {bootstrap_p}
  head_assignment: {head_assignment}
  model_args:
      hidden_size: 100
      add_rnn: true
      add_edge_model: true
      add_global_model: False
      x_encoding:
        - name: contribution
          n_levels: 21
          encoding: numeric
        - name: prev_punishment
          n_levels: 31
          encoding: numeric
        - etype: bool
          name: contribution_valid
        - etype: bool
          name: in_group
      b_encoding:
        - name: round_number
          n_levels: 32
          encoding: onehot

replay_memory_args:
  n_episodes: 100

n_update_steps: {n_update_steps}
eval_period: {eval_period}
training_batch_size: 1

env_args:
  n_groups: 2
  n_agents: 8
  agent_groups: [0, 0, 0, 0, 1, 1, 1, 1]
  rl_group_id: 0
  switch_every: 4
  n_contributions: 21
  n_punishments: 31
  n_rounds: 24
  batch_size: 1000
  reward_mode: common_pool

device: "cuda"
output_dir: "artifacts/manager/{job_id}"
basedir: "."
"""

RUN_BANNER = """\
# Budget: equal ENVIRONMENT EPISODES with the epsilon-greedy reference, not
# equal update steps. The mechanism changes which action is selected, not how
# many episodes are run, so 4000 update steps x 1000 parallel episodes +
# 200 evaluation rollouts x 1000 is the same 4,200,000 episodes the reference
# consumes. Counted, not argued: `rl_manager.EPISODE_BUDGET` increments on
# every rollout and the totals are printed at the end of each run on the
# `[budget]` line of its SLURM log.
# See notes/autoresearch_log/rl-manager-bootstrapped-dqn.md."""

PILOT_BANNER = """\
# PILOT -- a measurement of K, of head diversity and of the
# behaviour-versus-evaluated punishment gap. Not a result; do not read its
# policy."""


def write(job_id, seed, n_update_steps, eval_period, banner, **over):
    kwargs = dict(
        banner=banner,
        job_id=job_id,
        contribution_model=CONTRIBUTION_MODEL,
        switch_model=SWITCH_MODEL,
        opponent_punisher=OPPONENT_PUNISHER,
        valid_model=VALID_MODEL,
        seed=seed,
        n_update_steps=n_update_steps,
        eval_period=eval_period,
        exploration="bootstrap",
        n_heads=N_HEADS,
        bootstrap_p=BOOTSTRAP_P,
        head_assignment="per_episode",
    )
    kwargs.update(over)
    path = os.path.join(OUT_DIR, f"{job_id}.yml")
    with open(path, "w") as f:
        f.write(TEMPLATE.format(**kwargs))
    print(path)


def main():
    for seed in SEEDS:
        write(f"rl_bootstrap_s{seed}", seed, 4000, 20, RUN_BANNER)
    # K pilot: the four candidate ensemble sizes, same seed, 200 steps.
    for k in (1, 4, 10, 20):
        write(
            f"rl_bootstrap_pilot_k{k}",
            42,
            200,
            10,
            PILOT_BANNER,
            n_heads=k,
            exploration="bootstrap" if k > 1 else "eps_greedy",
        )
    # The head-to-batch mapping check: the same K, one head for the whole
    # rollout instead of one per episode.
    write(
        "rl_bootstrap_pilot_k10_per_rollout",
        42,
        200,
        10,
        PILOT_BANNER,
        n_heads=10,
        head_assignment="per_rollout",
    )


if __name__ == "__main__":
    main()
