"""Emit the evolution-strategies training configs -- one per seed, plus a
cost pilot.

The arm's whole point is that ONE variable changes against
configs/training/rl_manager/rl_new_clones_s42.yml: how the behaviour policy is
produced. Everything else -- the four model artifacts, the opponent, the env,
the network architecture -- is lifted verbatim out of that file rather than
retyped, so the claim is mechanical and `check_contract.py` can assert it.

    python scripts/rl_es/make_configs.py
"""

import os

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT_DIR = os.path.join(ROOT, "configs/training/rl_manager")
REFERENCE = os.path.join(OUT_DIR, "rl_new_clones_s42.yml")

SEEDS = (42, 43, 44, 45, 46)

#: Every key copied unchanged from the reference config. `manager_args` comes
#: along whole: its `model_args` is the architecture under optimisation, and
#: `opt_args` / `gamma` / `target_update_freq` / `eps` are carried (and
#: ignored) only so the initial parameter vector is drawn from the same RNG
#: state as the DQN arm's -- see es_manager.train_manager_es.
SHARED_KEYS = (
    "artificial_humans",
    "artificial_humans_valid",
    "switch_model",
    "opponent_manager",
    "artificial_humans_model",
    "manager_args",
    "env_args",
    "device",
    "basedir",
)

HEADER = """\
# AUTOGENERATED by scripts/rl_es/make_configs.py -- do not hand-edit.
#
{banner}
#
# EVOLUTION STRATEGIES arm of the four-way exploration comparison
# (Salimans, Ho, Chen, Sidor and Sutskever, 2017). One variable changes
# against configs/training/rl_manager/rl_new_clones_s42.yml: the behaviour
# policy. There is NO action noise anywhere in this arm. Every policy that is
# ever run or scored is a fixed deterministic policy evaluated over complete
# episodes; the population members are the behaviour policies and the mean
# parameter vector is the evaluated one.
#
# BUDGET. Equal environment EPISODES, not update steps. One generation scores
# the whole population inside a single env rollout of batch_size episodes, so
# a generation consumes exactly the {batch} behaviour episodes that one DQN
# update step consumes, and `n_generations` equals the reference config's
# `n_update_steps`. Behaviour budget {behaviour} episodes; evaluation adds
# {n_evals} deterministic rollouts of {batch}, at the same intervals as the
# DQN arm.
#
# AXES. The generation index is written into the metrics parquet's
# `update_step` column. It is NOT a gradient step -- this method has none. It
# is an episode counter, and it counts the same episodes the DQN arm's
# `update_step` counts.
"""

BLOCKED_BANNER = """\
# Cleared to run. The contract guards pass on this tree
# (scripts/rl_es/pilot.py; evidence in
# plots/data_analysis/evaluation/rl_manager_es/):
#   * the initial parameter vector is bit-identical to the DQN arm's for the
#     same seed, so the paired comparison starts from the same policy;
#   * a single-member population rollout reproduces
#     rl_manager.run_batch(on_policy=True) exactly, which is what makes this
#     arm's evaluation the same evaluation the other arms run;
#   * the behaviour policy contains no action noise: replaying a generation's
#     perturbations reproduces its actions exactly.
# See notes/autoresearch_log/rl-manager-evolution-strategies.md."""

PILOT_BANNER = """\
# COST PILOT -- a wall-clock and signal-to-noise measurement, not a result.
# Nothing it produces is science; do not read its policy as an outcome."""


def load_reference():
    with open(REFERENCE) as f:
        return yaml.safe_load(f)


def build(ref, job_id, seed, n_generations, eval_period, es_args):
    cfg = {k: ref[k] for k in SHARED_KEYS}
    cfg["job_id"] = job_id
    cfg["seed"] = seed
    cfg["n_generations"] = n_generations
    cfg["eval_period"] = eval_period
    cfg["es_args"] = es_args
    cfg["output_dir"] = f"artifacts/manager/{job_id}"
    return cfg


def write(cfg, ref, banner):
    batch = ref["env_args"]["batch_size"]
    header = HEADER.format(
        banner=banner,
        batch=batch,
        behaviour=cfg["n_generations"] * batch,
        n_evals=-(-cfg["n_generations"] // cfg["eval_period"]),
    )
    path = os.path.join(OUT_DIR, f"{cfg['job_id']}.yml")
    with open(path, "w") as f:
        f.write(header)
        f.write("\n")
        yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)
    print(path)


#: Every number here is read off a measurement; the decision record is in
#: notes/autoresearch_log/rl-manager-evolution-strategies.md.
#:
#: population_size 40 -- 1000/40 = 25 episodes per member, and the batch
#:   partition is exact. Between-member fitness spread over within-member
#:   standard error is 2.4 at the initialisation, comfortably above 1.
#:
#: sigma 0.05 -- NOT the paper's 0.02, and the reason is measured rather than
#:   preferred. This policy reads a discrete argmax over 31 ordinal actions.
#:   At the policy the run actually reaches after a few generations (mean
#:   punishment driven to exactly 0), sigma 0.02 leaves all 40 members
#:   implementing the identical zero policy -- signal to noise 0.86, below 1,
#:   nothing to rank. At 0.05, 18 of 40 members are off the zero plateau and
#:   the ratio is 2.0. At 0.1 the perturbation itself destroys the policy
#:   (population mean fitness 530 against 1423). See noise_plateau.csv.
#:
#: lr 0.001 -- NOT the paper's 0.01, for a reason that is arithmetic. Adam
#:   normalises per coordinate, so a step is |dtheta| ~ lr * sqrt(78532) = 2.8
#:   at lr 0.01, against |theta| ~ 18 at the initialisation: a 15% relative
#:   change per generation, driven by a rank vector that is at best half
#:   signal. Over 4000 generations the random-walk component alone inflates
#:   |theta| about tenfold, which shrinks sigma RELATIVE to the weights and
#:   re-creates the degenerate population that sigma was raised to avoid. The
#:   40-generation pilot at lr 0.01 collapsed to zero punishment by generation
#:   7 and spent the remaining 33 generations random-walking with |theta|
#:   climbing 0.21 per generation. At lr 0.001 the same first move takes ~70
#:   generations and leaves the rest of the budget for the question this arm
#:   exists to ask.
#:
#: l2 0.005 is the paper's and is kept, with the caveat recorded in the log
#:   that at this gradient scale it is negligible; lr is what bounds the walk.
ES_ARGS = {
    "population_size": 40,
    "sigma": 0.05,
    "lr": 0.001,
    "l2_coeff": 0.005,
    "mirrored": True,
    "fitness_shaping": "centered_rank",
}


def main():
    ref = load_reference()
    for seed in SEEDS:
        write(
            build(ref, f"rl_es_s{seed}", seed, 4000, 20, ES_ARGS),
            ref,
            BLOCKED_BANNER,
        )
    # The cost/guard pilot, and the shakeout that checks the two settings
    # above actually hold the population off the zero plateau for longer than
    # the first pilot managed.
    write(build(ref, "rl_es_pilot", 42, 40, 10, ES_ARGS), ref, PILOT_BANNER)
    write(build(ref, "rl_es_shakeout", 42, 200, 20, ES_ARGS), ref, PILOT_BANNER)


if __name__ == "__main__":
    main()
