"""Emit the evolution-strategies training configs -- one per seed, plus a
cost pilot.

The arm's whole point is that ONE variable changes against
configs/training/rl_manager/rl_new_clones_s42.yml: how the behaviour policy is
produced. Everything else -- the four model artifacts, the opponent, the env,
the network architecture -- is lifted verbatim out of that file rather than
retyped, so the claim is mechanical and `check_contract.py` can assert it.

    python scripts/rl_es/make_configs.py
"""

import os

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT_DIR = os.path.join(ROOT, "configs/training/rl_manager")
REFERENCE = os.path.join(OUT_DIR, "rl_new_clones_s42.yml")

SEEDS = (42, 43, 44, 45, 46)

#: Every key copied unchanged from the reference config. `manager_args` comes
#: along whole: its `model_args` is the architecture under optimisation, and
#: `opt_args` / `gamma` / `target_update_freq` / `eps` are carried (and
#: ignored) only so the initial parameter vector is drawn from the same RNG
#: state as the DQN arm's -- see es_manager.train_manager_es.
SHARED_KEYS = (
    "artificial_humans",
    "artificial_humans_valid",
    "switch_model",
    "opponent_manager",
    "artificial_humans_model",
    "manager_args",
    "env_args",
    "device",
    "basedir",
)

HEADER = """\
# AUTOGENERATED by scripts/rl_es/make_configs.py -- do not hand-edit.
#
{banner}
#
# EVOLUTION STRATEGIES arm of the four-way exploration comparison
# (Salimans, Ho, Chen, Sidor and Sutskever, 2017). One variable changes
# against configs/training/rl_manager/rl_new_clones_s42.yml: the behaviour
# policy. There is NO action noise anywhere in this arm. Every policy that is
# ever run or scored is a fixed deterministic policy evaluated over complete
# episodes; the population members are the behaviour policies and the mean
# parameter vector is the evaluated one.
#
# BUDGET. Equal environment EPISODES, not update steps. One generation scores
# the whole population inside a single env rollout of batch_size episodes, so
# a generation consumes exactly the {batch} behaviour episodes that one DQN
# update step consumes, and `n_generations` equals the reference config's
# `n_update_steps`. Behaviour budget {behaviour} episodes; evaluation adds
# {n_evals} deterministic rollouts of {batch}, at the same intervals as the
# DQN arm.
#
# AXES. The generation index is written into the metrics parquet's
# `update_step` column. It is NOT a gradient step -- this method has none. It
# is an episode counter, and it counts the same episodes the DQN arm's
# `update_step` counts.
"""

BLOCKED_BANNER = """\
# Cleared to run. The contract guards pass on this tree
# (scripts/rl_es/pilot.py; evidence in
# plots/data_analysis/evaluation/rl_manager_es/):
#   * the initial parameter vector is bit-identical to the DQN arm's for the
#     same seed, so the paired comparison starts from the same policy;
#   * a single-member population rollout reproduces
#     rl_manager.run_batch(on_policy=True) exactly, which is what makes this
#     arm's evaluation the same evaluation the other arms run;
#   * the behaviour policy contains no action noise: replaying a generation's
#     perturbations reproduces its actions exactly.
# See notes/autoresearch_log/rl-manager-evolution-strategies.md."""

PILOT_BANNER = """\
# COST PILOT -- a wall-clock and signal-to-noise measurement, not a result.
# Nothing it produces is science; do not read its policy as an outcome."""


def load_reference():
    with open(REFERENCE) as f:
        return yaml.safe_load(f)


def build(ref, job_id, seed, n_generations, eval_period, es_args):
    cfg = {k: ref[k] for k in SHARED_KEYS}
    cfg["job_id"] = job_id
    cfg["seed"] = seed
    cfg["n_generations"] = n_generations
    cfg["eval_period"] = eval_period
    cfg["es_args"] = es_args
    cfg["output_dir"] = f"artifacts/manager/{job_id}"
    return cfg


def write(cfg, ref, banner):
    batch = ref["env_args"]["batch_size"]
    header = HEADER.format(
        banner=banner,
        batch=batch,
        behaviour=cfg["n_generations"] * batch,
        n_evals=-(-cfg["n_generations"] // cfg["eval_period"]),
    )
    path = os.path.join(OUT_DIR, f"{cfg['job_id']}.yml")
    with open(path, "w") as f:
        f.write(header)
        f.write("\n")
        yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)
    print(path)


def main():
    ref = load_reference()
    # Population and noise scale: see the decision record in
    # notes/autoresearch_log/rl-manager-evolution-strategies.md. 40 members
    # over a 1000-episode batch is 25 episodes each; sigma, learning rate and
    # L2 are the paper's own defaults.
    es_args = {
        "population_size": 40,
        "sigma": 0.02,
        "lr": 0.01,
        "l2_coeff": 0.005,
        "mirrored": True,
        "fitness_shaping": "centered_rank",
    }
    for seed in SEEDS:
        write(
            build(ref, f"rl_es_s{seed}", seed, 4000, 20, es_args),
            ref,
            BLOCKED_BANNER,
        )
    write(
        build(ref, "rl_es_pilot", 42, 40, 10, es_args),
        ref,
        PILOT_BANNER,
    )


if __name__ == "__main__":
    main()
