artificial_humans:
  full:
    contribution_model: artifacts/behavioral_cloning/21_contribution_model_v4/model/architecture_node+edge+rnn__dataset_full.pt
    valid_model: artifacts/behavioral_cloning/22_contribution_valid_model_v4/model/rnn_False__dataset_full.pt
managers:
  humanlike:
    type: human
    path: artifacts/behavioral_cloning/23_punishment_autoregressive_v4/model/architecture_node+edge.pt
    autoregressive: true
  baseline_pr4:
    type: rl
    path: artifacts/manager/01_rnn_node_v2/model/raven_per_group_manager.pt
  after_pr6:
    type: rl
    path: artifacts/manager/01_rnn_node/model/raven_per_group_manager.pt

n_episode_steps: 24
n_episodes: 100
output_dir: artifacts/simulation/01_compare_v3
base_dir: .
