artificial_humans:
  full:
    contribution_model: artifacts/behavioral_cloning/21_contribution_model_v4/model/architecture_node+edge+rnn__dataset_full.pt
    valid_model: artifacts/behavioral_cloning/22_contribution_valid_model_v4/model/rnn_False__dataset_full.pt
managers:
  humanlike:
    type: human
    path: artifacts/behavioral_cloning/23_punishment_autoregressive_v4/model/architecture_node+edge.pt
    autoregressive: true
  optimal_old:
    type: rl
    path: artifacts/manager/17_exp2_group_payoff_heavy_optimize/model/_manager.pt
  raven_grouped_#26:
    type: rl
    path: artifacts/manager/01_rnn_node/model/raven_per_group_manager.pt
  raven_common_good_#26:
    type: rl
    path: artifacts/manager/01_rnn_node/model/raven_common_good.pt

n_episode_steps: 32
n_episodes: 100
output_dir: artifacts/simulation/01_compare
base_dir: .
